version: '3.8'

services:
  email-reader:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    container_name: email-reader-app
    ports:
      - "8000:8000"
    volumes:
      - /path/to/your/email/folder:/app/emails:ro
      - ./logs:/app/logs
    environment:
      - EMAIL_FOLDER_PATH=/app/emails
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: email-reader-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - email-reader
    restart: unless-stopped

volumes:
  logs:
