Return-Path: <caldogg4@gmail.com>
Received: from mail-qk1-f198.google.com (209.85.222.198) by satipe.disaki.es for <Themole@goingunderground.net>; Thu, 18 Sep 2025 16:06:40 +0200 (envelope-from <caldogg4@gmail.com>)
Received: by mail-qk1-f198.google.com with SMTP id af79cd13be357-827887699easo190029785a.1
        for <Themole@goingunderground.net>; Thu, 18 Sep 2025 07:06:39 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20230601; t=1758204399; x=1758809199; darn=goingunderground.net;
        h=to:from:subject:date:message-id:mime-version:from:to:cc:subject
         :date:message-id:reply-to;
        bh=+f29bxLEwfthE3Bwk7HI454IaX5ttVP3TzChAgjQ8qM=;
        b=TI5lQO13FMe93Z3CJ+6c2TD+tzo5kzrZYYm2Ugz4aKlV57sYOz0bxgjBI4yOGdzQh9
         wPuUFu7SqeFFvySA+rK9+uhAvrwqJYeOwhz3x9GfGUjX+WacINiVU4hpdmggTZFw0XGH
         L9qVlBhvguFXc0IBrj8SQ+nRbgDAMAoMd4Jx7tGgK6BBo08R1d71ZnV1PAucSVYe6qbh
         ydKzrStHFffN17TJtrSIL1zrAuI9iZuEeHFNotJgpWlvUKD4yB+esEO6zTYRZUbveD5t
         0lggjBESNRHUnTsoJHapTS49dX4m++ubWjwByYa+XYzx77y8cqu1PdkLDeeANngp5oh8
         AtyA==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1758204399; x=1758809199;
        h=to:from:subject:date:message-id:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=+f29bxLEwfthE3Bwk7HI454IaX5ttVP3TzChAgjQ8qM=;
        b=klU20DBaZukK5Eget08CHYrCTsN1P2gA5iF9llDVRDJPV0f8l1Kd3/kOVeUDUuxXcd
         O6O0+/8bycxKAxkTbuIsV4n7EUHBX98HY7foOsGCECT+3y4dH6Nf9iy5rE6A3wDQJF57
         jgw3JFLdWoafGXeOK3Hw1aMZ4tU7aAsOsVApUQiHeYuLnSpgphtEu9/64nlRV7aeabfY
         4kZHMfEarb7La+LXxugV/y2a6a9I0VTZHmx4V8okS/2CaQdx4ybErPd/W4pJ5tLljLE+
         mAFNOuvnch591Xp7WWoW85CQ4YaAdM21yNFxccG39+r3HCOf6Foe4fhS+PwmC5LDjBzb
         8Byg==
X-Gm-Message-State: AOJu0YwxeoGG8ui28zNpCkBcvR3V6Mj8TrfundHwqShm1eOk+vCIhBrv
	3V7xwotjYIaET5QmbhH2JC6rddhB1OExC9CYHRPsHFRgUVNIDhmw9pCgwmB72kvuIf+dVaBnxp3
	lXcA=
X-Google-Smtp-Source: AGHT+IFiYrYhF/hRrbeI9VvfzufLsAbte5pswVl0kjmimylJmkw1NWvoDnqQytgMNcB5MAb8tj4hwkswZQ==
MIME-Version: 1.0
X-Received: by 2002:a05:620a:46a0:b0:7e8:46ff:baac with SMTP id
 af79cd13be357-8310afd8038mr672108885a.1.1758204398907; Thu, 18 Sep 2025
 07:06:38 -0700 (PDT)
Message-ID: <autogen-java-012fc800-434c-4f5f-b4a7-6e847b51b655@google.com>
Date: Thu, 18 Sep 2025 14:06:38 +0000
Subject: Themole@goingunderground.net, My Patience is Basically Like A Gift
 Card Not Sure T-Shirt
From: caldogg4@gmail.com
To: Themole@goingunderground.net
Content-Type: multipart/alternative; boundary="000000000000a3c36b063f13dc53"

--000000000000a3c36b063f13dc53
Content-Type: text/plain; charset="UTF-8"; format=flowed; delsp=yes
Content-Transfer-Encoding: base64

zY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDN
jyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2P
IOKAjCDNjyDigIwgzY8gIA0K4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwg
zY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDN
jyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PICANCuKAjCDNjyDigIwgzY8g4oCM
IM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwg
zY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDN
jyAgDQrigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCM
IM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwg
zY8g4oCMIM2PIOKAjCDNjyDigIwgzY8gIA0K4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKA
jCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCM
IM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PICANCuKAjCDNjyDi
gIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKA
jCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCM
IM2PIOKAjCDNjyAgDQrigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDi
gIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKA
jCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8gIA0K4oCMIM2PIOKAjCDNjyDigIwgzY8g
4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDi
gIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PICAN
CuKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g
4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDi
gIwgzY8g4oCMIM2PIOKAjCDNjyAgDQrigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2P
IOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g
4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8gIA0K4oCMIM2PIOKAjCDN
jyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2P
IOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g
4oCMIM2PICANCuKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDN
jyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2P
IOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyAgDQrigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwg
zY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDN
jyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8gIA0K4oCM
IM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwg
zY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDN
jyDigIwgzY8g4oCMIM2PICANCuKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCM
IM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwg
zY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyAgDQrigIwgzY8g4oCMIM2PIOKA
jCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCM
IM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwg
zY8gIA0K4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKA
jCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCMIM2PIOKAjCDNjyDigIwgzY8g4oCM
IM2PIOKAjA0KDQoNCg0KTXkgUGF0aWVuY2UgaXMgQmFzaWNhbGx5IExpa2UgQSBHaWZ0IENhcmQg
Tm90IFN1cmUgVC1TaGlydA0KDQoNCg0KDQpQcmVzaHJ1bmsgdC1zaGlydCBpbiAxMDAlIGNvdHRv
biwgZXhjZXB0Og0KDQoNCg0KU3BvcnQgR3JleTogOTAlIFVTIENvdHRvbiAvIDEwJSBQb2x5ZXN0
ZXINCg0KDQpEYXJrIEhlYXRoZXI6IDUwJSBVUyBDb3R0b24gLyA1MCUgUG9seWVzdGVyIG9yIDM1
JSBVUyBDb3R0b24gLyA2NSUgUG9seWVzdGVyDQoNCg0KQXNoOiA5OSUgVVMgQ290dG9uIC8gMSUg
UG9seWVzdGVyDQoNCg0KU2VhbWxlc3MgdHdpbiBuZWVkbGUgNy84IiBjb2xsYXIuDQoNClRhcGVk
IG5lY2sgYW5kIHNob3VsZGVycy4gUm9sbGVkIGZvcndhcmQgc2hvdWxkZXJzIGZvciBiZXR0ZXIg
Zml0Lg0KDQpUd2luIG5lZWRsZSBzbGVldmUgYW5kIGJvdHRvbSBoZW1zLiBRdWFydGVyLXR1cm5l
ZCB0byBlbGltaW5hdGUgY2VudHJlICANCmNyZWFzZS4NCg0KDQoNClNIT1AgTk9XDQoNCg0KV2Fu
dCB0byBjaGFuZ2UgaG93IHlvdSByZWNlaXZlIHRoZXNlIGVtYWlscz8NCllvdSBjYW4gdXBkYXRl
IHlvdXIgcHJlZmVyZW5jZXMgb3IgdW5zdWJzY3JpYmUNCg0KDQoNCg0KRW1haWwgTWFya2V0aW5n
IFBvd2VyZWQgYnkgTWFpbGNoaW1wDQoNCg0KDQoNCg==
--000000000000a3c36b063f13dc53
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html><html xmlns=3D"http://www.w3.org/1999/xhtml" xmlns:v=3D"urn:=
schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-microsoft-com:office:offi=
ce"><head><!--[if gte mso 15]><xml><o:OfficeDocumentSettings><o:AllowPNG/><=
o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![end=
if]--><meta charset=3D"UTF-8"/><meta http-equiv=3D"X-UA-Compatible" content=
=3D"IE=3Dedge"/><meta name=3D"viewport" content=3D"width=3Ddevice-width, in=
itial-scale=3D1"/><title></title><link rel=3D"preconnect" href=3D"https://f=
onts.googleapis.com"/><link rel=3D"preconnect" href=3D"https://fonts.gstati=
c.com" crossorigin=3D""/><!--[if !mso]><!--><link rel=3D"stylesheet" type=
=3D"text/css" id=3D"newGoogleFontsStatic" href=3D"https://fonts.googleapis.=
com/css?family=3DMontserrat:400,400i,700,700i,900,900i"/><!--<![endif]--><s=
tyle>img{-ms-interpolation-mode:bicubic;}table, td{mso-table-lspace:0pt;mso=
-table-rspace:0pt;}.mceStandardButton, .mceStandardButton td, .mceStandardB=
utton td a{mso-hide:all!important;}p, a, li, td, blockquote{mso-line-height=
-rule:exactly;}p, a, li, td, body, table, blockquote{-ms-text-size-adjust:1=
00%;-webkit-text-size-adjust:100%;}.mcnPreviewText{display:none!important;}=
.bodyCell{margin:0 auto;padding:0;width:100%;}.ExternalClass, .ExternalClas=
s p, .ExternalClass td, .ExternalClass div, .ExternalClass span, .ExternalC=
lass font{line-height:100%;}.ReadMsgBody, .ExternalClass{width:100%;}a[x-ap=
ple-data-detectors]{color:inherit!important;text-decoration:none!important;=
font-size:inherit!important;font-family:inherit!important;font-weight:inher=
it!important;line-height:inherit!important;}body{height:100%;margin:0;paddi=
ng:0;width:100%;background:#ffffff;}p{margin:0;padding:0;}table{border-coll=
apse:collapse;}td, p, a{word-break:break-word;}h1, h2, h3, h4, h5, h6{displ=
ay:block;margin:0;padding:0;}img, a img{border:0;height:auto;outline:none;t=
ext-decoration:none;}a[href^=3D"tel"], a[href^=3D"sms"]{color:inherit;curso=
r:default;text-decoration:none;}.mceColumn .mceButtonLink,.mceColumn-1 .mce=
ButtonLink,.mceColumn-2 .mceButtonLink,.mceColumn-3 .mceButtonLink,.mceColu=
mn-4 .mceButtonLink{min-width:30px;}div[contenteditable=3D"true"]{outline:0=
;}.mceImageBorder{display:inline-block;}.mceImageBorder img{border:0!import=
ant;}body, #bodyTable{background-color:rgb(244, 244, 244);}.mceText, .mcnTe=
xtContent, .mceLabel{font-family:"Helvetica Neue", Helvetica, Arial, Verdan=
a, sans-serif;}.mceText, .mcnTextContent, .mceLabel{color:rgb(0, 0, 0);}.mc=
eText h1, .mceText p, .mceText ul, .mceText label, .mceText input{margin-bo=
ttom:0;}.mceSpacing-12 .mceInput + .mceErrorMessage{margin-top:-6px;}.mceSp=
acing-24 .mceInput + .mceErrorMessage{margin-top:-12px;}.mceInput{backgroun=
d-color:transparent;border:2px solid rgb(208, 208, 208);width:60%;color:rgb=
(77, 77, 77);display:block;}.mceInput[type=3D"radio"], .mceInput[type=3D"ch=
eckbox"]{float:left;margin-right:12px;display:inline;width:auto!important;}=
.mceLabel > .mceInput{margin-bottom:0;margin-top:2px;}.mceLabel{display:blo=
ck;}.mceText p, .mcnTextContent p{color:rgb(0, 0, 0);font-family:"Helvetica=
 Neue", Helvetica, Arial, Verdana, sans-serif;font-size:16px;font-weight:no=
rmal;line-height:1.5;mso-line-height-alt:150%;text-align:center;letter-spac=
ing:0;direction:ltr;margin:0;}.mceText h1, .mcnTextContent h1{color:rgb(0, =
0, 0);font-family:"Helvetica Neue", Helvetica, Arial, Verdana, sans-serif;f=
ont-size:31px;font-weight:bold;line-height:1.5;mso-line-height-alt:150%;tex=
t-align:left;letter-spacing:0;direction:ltr;}.mceText a, .mcnTextContent a{=
color:rgb(0, 0, 0);font-style:normal;font-weight:normal;text-decoration:und=
erline;direction:ltr;}p.mcePastedContent, h1.mcePastedContent, h2.mcePasted=
Content, h3.mcePastedContent, h4.mcePastedContent{text-align:left;}#d15 p, =
#d15 h1, #d15 h2, #d15 h3, #d15 h4, #d15 ul{text-align:center;}@media only =
screen and (max-width: 480px) {body, table, td, p, a, li, blockquote{-webki=
t-text-size-adjust:none!important;}body{width:100%!important;min-width:100%=
!important;}body.mobile-native{-webkit-user-select:none;user-select:none;tr=
ansition:transform 0.2s ease-in;transform-origin:top center;}colgroup{displ=
ay:none;}.mceLogo img, .mceImage img, .mceSocialFollowIcon img{height:auto!=
important;}.mceWidthContainer{max-width:660px!important;}.mceColumn, .mceCo=
lumn-2{display:block!important;width:100%!important;}.mceColumn-forceSpan{d=
isplay:table-cell!important;width:auto!important;}.mceColumn-forceSpan .mce=
Button a{min-width:0!important;}.mceReverseStack{display:table;width:100%;}=
.mceColumn-1{display:table-footer-group;width:100%!important;}.mceColumn-3{=
display:table-header-group;width:100%!important;}.mceColumn-4{display:table=
-caption;width:100%!important;}.mceKeepColumns .mceButtonLink{min-width:0;}=
.mceBlockContainer, .mceSpacing-24{padding-right:16px!important;padding-lef=
t:16px!important;}.mceBlockContainerE2E{padding-right:0;padding-left:0;}.mc=
eImage, .mceLogo{width:100%!important;height:auto!important;}.mceText img{m=
ax-width:100%!important;}.mceFooterSection .mceText, .mceFooterSection .mce=
Text p{font-size:16px!important;line-height:140%!important;}.mceText p{marg=
in:0;font-size:16px!important;line-height:1.5!important;mso-line-height-alt=
:150%;}.mceText h1{font-size:31px!important;line-height:1.5!important;mso-l=
ine-height-alt:150%;}.bodyCell{padding-left:16px!important;padding-right:16=
px!important;}.mceButtonContainer{width:fit-content!important;max-width:fit=
-content!important;}.mceButtonLink{padding:18px 28px!important;font-size:16=
px!important;}#b7, #b21 .mceTextBlockContainer, #b22 .mceTextBlockContainer=
{padding:12px 24px!important;}#b7 table{margin-left:auto!important;margin-r=
ight:auto!important;float:none!important;}#b9 table{float:none!important;ma=
rgin:0 auto!important;}#b9{padding:12px 48px!important;}#b9 .mceButtonLink{=
padding-top:16px!important;padding-bottom:16px!important;}#b15 .mceTextBloc=
kContainer{padding:12px 16px!important;}#gutterContainerId-15, #gutterConta=
inerId-21, #gutterContainerId-22{padding:0!important;}}@media only screen a=
nd (max-width: 640px) {.mceClusterLayout td{padding:4px!important;}}</style=
></head><body><!--*|IF:MC_PREVIEW_TEXT|*--><!--[if !gte mso 9]><!----><span=
 class=3D"mcnPreviewText" style=3D"display:none; font-size:0px; line-height=
:0px; max-height:0px; max-width:0px; opacity:0; overflow:hidden; visibility=
:hidden; mso-hide:all;"></span><!--<![endif]--><!--*|END:IF|*--><div style=
=3D"display: none; max-height: 0px; overflow: hidden;">=CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=
=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =
=CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=
=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =
=E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=
=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=
=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =
=C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=
=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =
=E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=80=87  =CD=8F =E2=80=8C =C2=A0 =E2=
=80=87=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD=
 =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD</div><!-=
-MCE_TRACKING_PIXEL--><center><table border=3D"0" cellpadding=3D"0" cellspa=
cing=3D"0" height=3D"100%" width=3D"100%" id=3D"bodyTable" style=3D"backgro=
und-color: rgb(244, 244, 244);"><tbody><tr><td class=3D"bodyCell" align=3D"=
center" valign=3D"top"><table id=3D"root" border=3D"0" cellpadding=3D"0" ce=
llspacing=3D"0" width=3D"100%"><tbody data-block-id=3D"5" class=3D"mceWrapp=
er"><tr><td style=3D"background-color:transparent" valign=3D"top" align=3D"=
center" class=3D"mceSectionHeader"><!--[if (gte mso 9)|(IE)]><table align=
=3D"center" border=3D"0" cellspacing=3D"0" cellpadding=3D"0" width=3D"660" =
style=3D"width:660px;"><tr><td><![endif]--><table border=3D"0" cellpadding=
=3D"0" cellspacing=3D"0" width=3D"100%" style=3D"max-width:660px" role=3D"p=
resentation"><tbody><tr><td style=3D"background-color:#ffffff" valign=3D"to=
p" class=3D"mceWrapperInner"><table align=3D"center" border=3D"0" cellpaddi=
ng=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"presentation" data-block-=
id=3D"4"><tbody><tr class=3D"mceRow"><td style=3D"background-position:cente=
r;background-repeat:no-repeat;background-size:cover" valign=3D"top"><table =
border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"pre=
sentation"><tbody><tr><td style=3D"padding-top:0;padding-bottom:0" valign=
=3D"top" class=3D"mceColumn" id=3D"mceColumnId--4" data-block-id=3D"-4" col=
span=3D"12" width=3D"100%"><table border=3D"0" cellpadding=3D"0" cellspacin=
g=3D"0" width=3D"100%" role=3D"presentation"><tbody><tr><td style=3D"backgr=
ound-color:transparent;border:0;border-radius:0" valign=3D"top" id=3D"b2"><=
table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=
=3D"presentation" data-block-id=3D"2"><tbody><tr><td valign=3D"top" class=
=3D"mceSpacerBlock" height=3D"20"></td></tr></tbody></table></td></tr><tr><=
td style=3D"padding-top:0;padding-bottom:0;padding-right:0;padding-left:0" =
valign=3D"top" class=3D"mceGutterContainer" id=3D"gutterContainerId-21"><ta=
ble border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" style=
=3D"border-collapse:separate" role=3D"presentation"><tbody><tr><td style=3D=
"padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;border:0;bor=
der-radius:0" valign=3D"top" id=3D"b21"><table width=3D"100%" style=3D"bord=
er:0;background-color:transparent;border-radius:0;border-collapse:separate"=
><tbody><tr><td style=3D"padding-left:24px;padding-right:24px;padding-top:1=
2px;padding-bottom:12px" class=3D"mceTextBlockContainer"><div data-block-id=
=3D"21" class=3D"mceText" id=3D"d21" style=3D"width:100%"><p style=3D"text-=
align: center;"><br/></p><p style=3D"text-align: center;"><br/></p><h1 clas=
s=3D"title-campaign md-h2 mb-0 mb-md-3 sen-text-truncate last-child" style=
=3D"box-sizing: border-box; margin-bottom: 1rem !important; margin-top: 0px=
; line-height: 1.2; font-variant-ligatures: normal; font-variant-caps: norm=
al; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0p=
x; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-=
width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text=
-decoration-thickness: initial; text-decoration-style: initial; text-decora=
tion-color: initial; mso-line-height-alt: 120%;"><span style=3D"background-=
color: rgb(255, 255, 255)">My Patience is Basically Like A Gift Card Not Su=
re T-Shirt</span></h1></div></td></tr></tbody></table></td></tr></tbody></t=
able></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody>=
</table></td></tr></tbody></table><!--[if (gte mso 9)|(IE)]></td></tr></tab=
le><![endif]--></td></tr></tbody><tbody data-block-id=3D"13" class=3D"mceWr=
apper"><tr><td style=3D"background-color:transparent" valign=3D"top" align=
=3D"center" class=3D"mceSectionBody"><!--[if (gte mso 9)|(IE)]><table align=
=3D"center" border=3D"0" cellspacing=3D"0" cellpadding=3D"0" width=3D"660" =
style=3D"width:660px;"><tr><td><![endif]--><table border=3D"0" cellpadding=
=3D"0" cellspacing=3D"0" width=3D"100%" style=3D"max-width:660px" role=3D"p=
resentation"><tbody><tr><td style=3D"background-color:#ffffff" valign=3D"to=
p" class=3D"mceWrapperInner"><table align=3D"center" border=3D"0" cellpaddi=
ng=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"presentation" data-block-=
id=3D"12"><tbody><tr class=3D"mceRow"><td style=3D"background-position:cent=
er;background-repeat:no-repeat;background-size:cover" valign=3D"top"><table=
 border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"pr=
esentation"><tbody><tr><td style=3D"padding-top:0;padding-bottom:0" valign=
=3D"top" class=3D"mceColumn" id=3D"mceColumnId--5" data-block-id=3D"-5" col=
span=3D"12" width=3D"100%"><table border=3D"0" cellpadding=3D"0" cellspacin=
g=3D"0" width=3D"100%" role=3D"presentation"><tbody><tr><td style=3D"backgr=
ound-color:transparent;padding-top:12px;padding-bottom:12px;padding-right:2=
4px;padding-left:24px;border:0;border-radius:0" valign=3D"top" class=3D"mce=
ImageBlockContainer" align=3D"center" id=3D"b7"><div><!--[if !mso]><!--></d=
iv><a href=3D"https://edana.pro/vi/my-patience-is-basically-like-a-gift-car=
d-not-sure-t-shirt" style=3D"display:block" target=3D"_blank" data-block-id=
=3D"7"><table align=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=
=3D"0" width=3D"85%" style=3D"border-collapse:separate;margin:0;vertical-al=
ign:top;max-width:85%;width:85%;height:auto" role=3D"presentation" data-tes=
tid=3D"image-7"><tbody><tr><td style=3D"border:0;border-radius:0;margin:0" =
valign=3D"top"><img alt=3D"" src=3D"https://mcusercontent.com/e3702f8639c34=
6720fa953737/images/c6f1fd03-5c24-e67c-49ef-e515833377e5.png" width=3D"520.=
1999999999999" height=3D"auto" style=3D"display:block;max-width:100%;height=
:auto;border-radius:0" class=3D"imageDropZone mceImage"/></td></tr></tbody>=
</table></a><div><!--<![endif]--></div><div><!--[if mso]><a href=3D"https:/=
/edana.pro/vi/my-patience-is-basically-like-a-gift-card-not-sure-t-shirt"><=
span class=3D"mceImageBorder" style=3D"border:0;border-width:2px;vertical-a=
lign:top;margin:0"><img role=3D"presentation" class=3D"imageDropZone mceIma=
ge" src=3D"https://mcusercontent.com/e3702f8639c346720fa953737/images/c6f1f=
d03-5c24-e67c-49ef-e515833377e5.png" alt=3D"" width=3D"520.1999999999999" h=
eight=3D"auto" style=3D"display:block;max-width:520.1999999999999px;width:5=
20.1999999999999px;height:auto"/></span></a><![endif]--></div></td></tr><tr=
><td style=3D"padding-top:0;padding-bottom:0;padding-right:0;padding-left:0=
" valign=3D"top" class=3D"mceGutterContainer" id=3D"gutterContainerId-22"><=
table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" style=
=3D"border-collapse:separate" role=3D"presentation"><tbody><tr><td style=3D=
"padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;border:0;bor=
der-radius:0" valign=3D"top" id=3D"b22"><table width=3D"100%" style=3D"bord=
er:0;background-color:transparent;border-radius:0;border-collapse:separate"=
><tbody><tr><td style=3D"padding-left:24px;padding-right:24px;padding-top:1=
2px;padding-bottom:12px" class=3D"mceTextBlockContainer"><div data-block-id=
=3D"22" class=3D"mceText" id=3D"d22" style=3D"width:100%"><p><br/></p><p cl=
ass=3D"mcePastedContent"><br/></p><p class=3D"" style=3D"box-sizing: border=
-box; margin-bottom: 1rem; margin-top: 0px; font-variant-ligatures: normal;=
 font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orpha=
ns: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2;=
 word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; ba=
ckground-color: rgb(255, 255, 255); text-decoration-thickness: initial; tex=
t-decoration-style: initial; text-decoration-color: initial;"><span style=
=3D"background-color: rgb(255, 255, 255)">Preshrunk t-shirt in 100% cotton,=
 except:</span></p><ul style=3D"box-sizing: border-box; margin-bottom: 1rem=
; margin-top: 0px; color: rgb(33, 37, 41); font-family: Montserrat, sans-se=
rif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; f=
ont-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans=
: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; w=
ord-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; back=
ground-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-=
decoration-style: initial; text-decoration-color: initial;"><li><p class=3D=
"mcePastedContent"><span style=3D"color:rgb(33, 37, 41);"><span style=3D"fo=
nt-size: 16px"><span style=3D"font-family: Montserrat, sans-serif"><span st=
yle=3D"background-color: rgb(255, 255, 255)">Sport Grey:=C2=A090% US Cotton=
 / 10% Polyester</span></span></span></span></p></li><li><p class=3D"mcePas=
tedContent"><span style=3D"color:rgb(33, 37, 41);"><span style=3D"font-size=
: 16px"><span style=3D"font-family: Montserrat, sans-serif"><span style=3D"=
background-color: rgb(255, 255, 255)">Dark Heather: 50% US Cotton / 50% Pol=
yester or 35% US Cotton / 65% Polyester</span></span></span></span></p></li=
><li><p class=3D"mcePastedContent"><span style=3D"color:rgb(33, 37, 41);"><=
span style=3D"font-size: 16px"><span style=3D"font-family: Montserrat, sans=
-serif"><span style=3D"background-color: rgb(255, 255, 255)">Ash: 99% US Co=
tton / 1% Polyester</span></span></span></span></p></li></ul><p class=3D"" =
style=3D"box-sizing: border-box; margin-bottom: 1rem; margin-top: 0px; font=
-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; le=
tter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-=
transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0=
px; white-space: normal; background-color: rgb(255, 255, 255); text-decorat=
ion-thickness: initial; text-decoration-style: initial; text-decoration-col=
or: initial;"><span style=3D"color:rgb(33, 37, 41);"><span style=3D"font-si=
ze: 16px"><span style=3D"font-family: Montserrat, sans-serif"><span style=
=3D"background-color: rgb(255, 255, 255)">Seamless twin needle 7/8" collar.=
</span></span></span></span></p><p class=3D"" style=3D"box-sizing: border-b=
ox; margin-bottom: 1rem; margin-top: 0px; font-variant-ligatures: normal; f=
ont-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans=
: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; w=
ord-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; back=
ground-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-=
decoration-style: initial; text-decoration-color: initial;"><span style=3D"=
color:rgb(33, 37, 41);"><span style=3D"font-size: 16px"><span style=3D"font=
-family: Montserrat, sans-serif"><span style=3D"background-color: rgb(255, =
255, 255)">Taped neck and shoulders. Rolled forward shoulders for better fi=
t.</span></span></span></span></p><p class=3D"" style=3D"box-sizing: border=
-box; margin-bottom: 1rem; margin-top: 0px; font-variant-ligatures: normal;=
 font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orpha=
ns: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2;=
 word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; ba=
ckground-color: rgb(255, 255, 255); text-decoration-thickness: initial; tex=
t-decoration-style: initial; text-decoration-color: initial;"><span style=
=3D"color:rgb(33, 37, 41);"><span style=3D"font-size: 16px"><span style=3D"=
font-family: Montserrat, sans-serif"><span style=3D"background-color: rgb(2=
55, 255, 255)">Twin needle sleeve and bottom=C2=A0hems. Quarter-turned to e=
liminate centre crease.</span></span></span></span></p><p class=3D"mcePaste=
dContent last-child"><br/></p></div></td></tr></tbody></table></td></tr></t=
body></table></td></tr><tr><td style=3D"background-color:transparent;paddin=
g-top:12px;padding-bottom:12px;padding-right:48px;padding-left:48px;border:=
0;border-radius:0" valign=3D"top" class=3D"mceButtonBlockContainer" align=
=3D"center" id=3D"b9"><div><!--[if !mso]><!--></div><table align=3D"center"=
 border=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"presentation" dat=
a-block-id=3D"9" class=3D"mceButtonContainer"><tbody><tr class=3D"mceStanda=
rdButton"><td style=3D"background-color:#000000;border-radius:0;text-align:=
center" valign=3D"top" class=3D"mceButton"><a href=3D"https://edana.pro/vi/=
my-patience-is-basically-like-a-gift-card-not-sure-t-shirt" target=3D"_blan=
k" class=3D"mceButtonLink" style=3D"background-color:#000000;border-radius:=
0;border:2px solid #000000;color:#ffffff;display:block;font-family:'Helveti=
ca Neue', Helvetica, Arial, Verdana, sans-serif;font-size:16px;font-weight:=
normal;font-style:normal;padding:16px 28px;text-decoration:none;text-align:=
center;direction:ltr;letter-spacing:0px" rel=3D"noreferrer">SHOP NOW</a></t=
d></tr></tbody></table><div><!--<![endif]--></div><table align=3D"center" b=
order=3D"0" cellpadding=3D"0" cellspacing=3D"0" role=3D"presentation" data-=
block-id=3D"9" class=3D"mceButtonContainer"><tbody><tr><!--[if mso]><td ali=
gn=3D"center"><v:roundrect xmlns:v=3D"urn:schemas-microsoft-com:vml"xmlns:w=
=3D"urn:schemas-microsoft-com:office:word"href=3D"https://edana.pro/vi/my-p=
atience-is-basically-like-a-gift-card-not-sure-t-shirt"style=3D"v-text-anch=
or:middle; width:147.44px; height:53px;"arcsize=3D"0%"strokecolor=3D"#00000=
0"strokeweight=3D"2px"fillcolor=3D"#000000"><v:stroke dashstyle=3D"solid"/>=
<w:anchorlock /><center style=3D"color: #ffffff;display: block;font-family:=
 'Helvetica Neue', Helvetica, Arial, Verdana, sans-serif;font-size: 16;font=
-style: normal;font-weight: normal;letter-spacing: 0px;text-decoration: non=
e;text-align: center;direction: ltr;">SHOP NOW</center></v:roundrect></td><=
![endif]--></tr></tbody></table></td></tr><tr><td style=3D"background-color=
:transparent;border:0;border-radius:0" valign=3D"top" id=3D"b10"><table bor=
der=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"presen=
tation" data-block-id=3D"10"><tbody><tr><td valign=3D"top" class=3D"mceSpac=
erBlock" height=3D"20"></td></tr></tbody></table></td></tr></tbody></table>=
</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></tab=
le><!--[if (gte mso 9)|(IE)]></td></tr></table><![endif]--></td></tr></tbod=
y><tbody data-block-id=3D"19" class=3D"mceWrapper"><tr><td style=3D"backgro=
und-color:transparent" valign=3D"top" align=3D"center" class=3D"mceSectionF=
ooter"><!--[if (gte mso 9)|(IE)]><table align=3D"center" border=3D"0" cells=
pacing=3D"0" cellpadding=3D"0" width=3D"660" style=3D"width:660px;"><tr><td=
><![endif]--><table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=
=3D"100%" style=3D"max-width:660px" role=3D"presentation"><tbody><tr><td st=
yle=3D"background-color:#ffffff" valign=3D"top" class=3D"mceWrapperInner"><=
table align=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" wid=
th=3D"100%" role=3D"presentation" data-block-id=3D"18"><tbody><tr class=3D"=
mceRow"><td style=3D"background-position:center;background-repeat:no-repeat=
;background-size:cover" valign=3D"top"><table border=3D"0" cellpadding=3D"0=
" cellspacing=3D"0" width=3D"100%" role=3D"presentation"><tbody><tr><td sty=
le=3D"padding-top:0;padding-bottom:0" valign=3D"top" class=3D"mceColumn" id=
=3D"mceColumnId--6" data-block-id=3D"-6" colspan=3D"12" width=3D"100%"><tab=
le border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"=
presentation"><tbody><tr><td style=3D"padding-top:8px;padding-bottom:8px;pa=
dding-right:8px;padding-left:8px;border:0;border-radius:0" valign=3D"top" i=
d=3D"b17"><table align=3D"center" border=3D"0" cellpadding=3D"0" cellspacin=
g=3D"0" width=3D"100%" role=3D"presentation" data-block-id=3D"17" id=3D"sec=
tion_7d931912db6b2978a79fcf7a75b6efd3" class=3D"mceFooterSection"><tbody><t=
r class=3D"mceRow"><td style=3D"background-position:center;background-repea=
t:no-repeat;background-size:cover" valign=3D"top"><table border=3D"0" cellp=
adding=3D"0" cellspacing=3D"12" width=3D"100%" role=3D"presentation"><tbody=
><tr><td style=3D"padding-top:0;padding-bottom:0" valign=3D"top" class=3D"m=
ceColumn" id=3D"mceColumnId--3" data-block-id=3D"-3" colspan=3D"12" width=
=3D"100%"><table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"=
100%" role=3D"presentation"><tbody><tr><td style=3D"padding-top:0;padding-b=
ottom:0;padding-right:0;padding-left:0" valign=3D"top" class=3D"mceGutterCo=
ntainer" id=3D"gutterContainerId-15"><table border=3D"0" cellpadding=3D"0" =
cellspacing=3D"0" width=3D"100%" style=3D"border-collapse:separate" role=3D=
"presentation"><tbody><tr><td style=3D"padding-top:0;padding-bottom:0;paddi=
ng-right:0;padding-left:0;border:0;border-radius:0" valign=3D"top" align=3D=
"center" id=3D"b15"><table width=3D"100%" style=3D"border:0;background-colo=
r:transparent;border-radius:0;border-collapse:separate"><tbody><tr><td styl=
e=3D"padding-left:16px;padding-right:16px;padding-top:12px;padding-bottom:1=
2px" class=3D"mceTextBlockContainer"><div data-block-id=3D"15" class=3D"mce=
Text" id=3D"d15" style=3D"display:inline-block;width:100%"><p class=3D"last=
-child"><br/><span style=3D"font-size: 12px">Want to change how you receive=
 these emails?</span><br/><span style=3D"font-size: 12px">You can update yo=
ur</span><a href=3D"*|UPDATE_PROFILE|*"><span style=3D"font-size: 12px"> </=
span></a><span style=3D"font-size: 12px">preferences or </span><a href=3D"h=
ttps://forms.gle/cBFxS2LoSHy471jh9"><span style=3D"font-size: 12px">unsubsc=
ribe</span></a></p></div></td></tr></tbody></table></td></tr></tbody></tabl=
e></td></tr><tr><td style=3D"border:0;border-radius:0" valign=3D"top" class=
=3D"mceLayoutContainer" align=3D"center" id=3D"b-2"><table align=3D"center"=
 border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"pr=
esentation" data-block-id=3D"-2"><tbody><tr class=3D"mceRow"><td style=3D"b=
ackground-position:center;background-repeat:no-repeat;background-size:cover=
" valign=3D"top"><table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" wi=
dth=3D"100%" role=3D"presentation"><tbody><tr><td valign=3D"top" class=3D"m=
ceColumn" id=3D"mceColumnId--7" data-block-id=3D"-7" colspan=3D"12" width=
=3D"100%"><table border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"=
100%" role=3D"presentation"><tbody><tr><td style=3D"border:0;border-radius:=
0" valign=3D"top" align=3D"center" id=3D"b16"><div><div data-block-id=3D"16=
"><a href=3D"http://eepurl.com/jhSokc" target=3D"_blank" rel=3D"noopener no=
referrer"><img style=3D"max-width:100%" width=3D"137" height=3D"53" alt=3D"=
Email Marketing Powered by Mailchimp" title=3D"Mailchimp Email Marketing" s=
rc=3D"https://cdn-images.mailchimp.com/monkey_rewards/intuit-mc-rewards-2.p=
ng"/></a></div></div></td></tr></tbody></table></td></tr></tbody></table></=
td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table=
></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></ta=
ble></td></tr></tbody></table></td></tr></tbody></table><!--[if (gte mso 9)=
|(IE)]></td></tr></table><![endif]--></td></tr></tbody></table></td></tr></=
tbody></table></center><script type=3D"text/javascript"  src=3D"/78Xv8AKaWY=
/Pv_34nCa/DJ/OcifrpJzpGN8SV/PjhiD35gAgo/cBw3USk/Hbn0B"></script></body></ht=
ml>
--000000000000a3c36b063f13dc53--
