Return-Path: <mediainc2020@gmail.com>
Received: from mail-ed1-f49.google.com (209.85.208.49) by satipe.disaki.es for <support@eminenteffect.com>; Wed, 17 Sep 2025 16:44:34 +0200 (envelope-from <mediainc2020@gmail.com>)
Received: by mail-ed1-f49.google.com with SMTP id 4fb4d7f45d1cf-62f4273a404so2055191a12.0
        for <support@eminenteffect.com>; Wed, 17 Sep 2025 07:44:34 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20230601; t=1758120274; x=1758725074; darn=eminenteffect.com;
        h=to:subject:message-id:date:from:mime-version:from:to:cc:subject
         :date:message-id:reply-to;
        bh=cHBo63VXyHnGiOFZEmHHHRDrgXAcW7y46VndcoI20Us=;
        b=Uv1/hIGYWU9vRYWrfseYtcyTHR0k5b3zn6RMtfVI2KzHlrbhR/BoD0OF/wp1cfZhDf
         q5Y0L0/2b7a1R5GHayGatDGNCW0tOl88DQ4owhgcZOV+dCvl3wSzKYffAsrY9Pw7KqPu
         5tM9f03qIpnDnn/qLiFIz+nrKWBQwL9BMwBuiZTRWFrhz18dbXfpxRzpgrf4iin0ZcvS
         poxH9MEon+5PE6JGbAEUfclyKEBXcaIZvGRv2f/lCEZwPxTBhZUpz16kjmbqf72wemm4
         f558PqeM+N9JLPJa370OyQfZCRzrCSrzIhholL0bUtGjgp79dHI5nZ8u/7o+n0jRpyQY
         55vA==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1758120274; x=1758725074;
        h=to:subject:message-id:date:from:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=cHBo63VXyHnGiOFZEmHHHRDrgXAcW7y46VndcoI20Us=;
        b=a9CSM9N132oxS6evr/8EfePGkE5KlDdjQwKTy6aSdkUNx3rftspUf+vnnHsVvMvD19
         dc1D2GnO7WwbVB49j08D2GsSyN5l0tRzEvoCkAQrjHpCx6SPhNdzK+KN7qlHU3ZPlRIY
         ouVj58dzYvbba+KW0PAyBk94cjTtsROCwikwEEtt67HrcX4nKSFVbadRr32b3Q5rdVtL
         lob9JQNJjk4Lc1myyq5uXcl2Ksw7pFpimRdHEnLomey5/gpvV9/TsWleCUELpzCZVTM/
         6V3sd3dTu743Uc8zSQLQRCLIC+EcpsubYVSThjmiw05RobRoz7eYSOrrqROasdeXwXi/
         2uHw==
X-Gm-Message-State: AOJu0Yw77xR7mRrN4FTj+k+5LXoMS6p4EaFbDJakqrFMWHqclyRNwSkA
	DK/U2qeRwNWjLKpuO4SQoroO/8UybkMRQwq8sC6j89kzfOD9INL0cNg2sLJQ6ghup1NKI0+6BAr
	KjbUwnAR4Bi5HhgrtfDwFKRCVdKW5Ec3MrDQH
X-Gm-Gg: ASbGncssc37T58ur2XC6fd0KetPLxZcXQ85ZOoy85x/0twj3ohp2A6q98P7bAyyXaAG
	7fcjtxRBTx6DxlAj/augQq522tj58mh5yxN4vUAN4Qqs5McXhpsPb/5kFIrjCCxXE/OZwoK3Cbz
	YLksW2PV2LbnDx5ekWk/4MmCGawy0pJgCF0DPa9z65wuxp5zn6dI84InmK+FSXIp69MtviUEENS
	tj1civR
X-Google-Smtp-Source: AGHT+IGswWidvahDFrmpK9kd8V90hhkgwxfvbIsJY+0Gu8bvtwfKFJv0q4gRoxeal/MDvxrGe/IP9jHyWWUs513h4cM=
X-Received: by 2002:a17:907:7254:b0:b04:2dd0:98 with SMTP id
 a640c23a62f3a-b167ea63087mr806838266b.12.1758120273800; Wed, 17 Sep 2025
 07:44:33 -0700 (PDT)
MIME-Version: 1.0
From: Jan andre <mediainc2020@gmail.com>
Date: Wed, 17 Sep 2025 15:46:35 +0100
X-Gm-Features: AS18NWBoQ9IPbui7fVy7f8BXTWWd-jXIEtICu1rFIXdL_sUwyN-jpFT6JcZL4PI
Message-ID: <CAKaBx8v_VHhn5nf4ExJmQTfuaqx2jmUWLQM5M6W=Gq9_AR0qog@mail.gmail.com>
Subject: sdf
To: support@eminenteffect.com
Content-Type: multipart/alternative; boundary="0000000000006478ba063f004677"

--0000000000006478ba063f004677
Content-Type: text/plain; charset="UTF-8"

sdfsdf

--0000000000006478ba063f004677
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">sdfsdf</div>

--0000000000006478ba063f004677--
