Return-Path: <ruru@oriontv.net>
Received: from bbeangkm (81.143.236.200) by satipe.disaki.es for <ruru@oriontv.net>; Wed, 17 Sep 2025 17:07:03 +0200 (envelope-from <ruru@oriontv.net>)
Message-ID: <E9132B8774A78884AD023A874497B602D089@oriontv.net>
Reply-To: "ruru@oriontv.net" <ruru@oriontv.net>
From: "ruru@oriontv.net" <ruru@oriontv.net>
Subject: =?utf-8?B?0JHQvtC70LXQtSA0MDAwMCDQsdCw0Lcg0LTQsNC90L3Ri9GFINC60L7QvdGC?=
	=?utf-8?B?0LDQutGC0L7QsiDQutC+0LzQv9Cw0L3QuNC5INCg0KQgaHR0cHM6Ly90Lm1l?=
	=?utf-8?B?L3MvYmF6ZWRhbm5peHNwZWVkcy8=?=
Date: Wed, 17 Sep 2025 22:06:56 +0700
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_0FB8_01DC281F.61C35240"
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2900.5931
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.6157
Disposition-Notification-To: <ruru@oriontv.net>

This is a multi-part message in MIME format.

------=_NextPart_000_0FB8_01DC281F.61C35240
Content-Type: text/plain;
	charset="utf-8"
Content-Transfer-Encoding: base64

0JHQvtC70LXQtSA0MDAwMCDQsdCw0Lcg0LTQsNC90L3Ri9GFINC60L7QvdGC0LDQutGC0L7QsiDQ
utC+0LzQv9Cw0L3QuNC5INCg0KTCoGh0dHBzOi8vdC5tZS9zL2JhemVkYW5uaXhzcGVlZHMvDQo=

------=_NextPart_000_0FB8_01DC281F.61C35240
Content-Type: text/html;
	charset="utf-8"
Content-Transfer-Encoding: base64

PGh0bWw+PGhlYWQ+DQo8bWV0YSBjb250ZW50PSJ0ZXh0L2h0bWw7IGNoYXJzZXQ9dXRmLTgiIGh0
dHAtZXF1aXY9Q29udGVudC1UeXBlPg0KPG1ldGEgbmFtZT1HRU5FUkFUT1IgY29udGVudD0iTVNI
VE1MIDguMDAuNjAwMS4yMzU4OCI+DQo8c3R5bGU+PC9zdHlsZT4NCjwvaGVhZD4NCjxib2R5IGJn
Q29sb3I9IiNmZmZmZmYiPg0KPGRpdiBhbGlnbj1sZWZ0Pjxmb250IGZhY2U9QXJpYWw+PGZvbnQg
c2l6ZT01PtCR0L7Qu9C10LUgNDAwMDAg0LHQsNC3INC00LDQvdC90YvRhSDQutC+0L3RgtCw0LrR
gtC+0LIg0LrQvtC80L/QsNC90LjQuSDQoNCkJm5ic3A7PGEgaHJlZj0iaHR0cHM6Ly90Lm1lL3Mv
YmF6ZWRhbm5peHNwZWVkcy8iPmh0dHBzOi8vdC5tZS9zL2JhemVkYW5uaXhzcGVlZHMvPC9hPjwv
Zm9udD48L2ZvbnQ+PC9kaXY+PC9ib2R5PjwvaHRtbD4NCg==

------=_NextPart_000_0FB8_01DC281F.61C35240--
