Return-Path: <securemail-email.sen.nt@secure360.com>
Received: from secure360.com (116.48.135.133) by satipe.disaki.es for <argon@oriontv.net>; Wed, 17 Sep 2025 17:19:09 +0200 (envelope-from <securemail-email.sen.nt@secure360.com>)
From: Office365 oriontv.net<securemail-email.sen.nt@secure360.com>
To: argon@oriontv.net
Subject: Account security Update - Office365
Date: 17 Sep 2025 23:19:04 +0800
Message-ID: <20250917231904.CB7349933D7DC48E@secure360.com>
MIME-Version: 1.0
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<HTML><HEAD></HEAD>
<BODY>
<P style=3D"FONT-SIZE: medium; FONT-FAMILY: Arial, sans-serif; WHITE-SPACE:=
 normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: =
rgb(0,0,0); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: norm=
al; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: no=
rmal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; t=
ext-decoration-style: initial; text-decoration-color: initial"><IMG style=
=3D"HEIGHT: 108px; WIDTH: 232px" alt=3D"Microsoft Office 365 &#8226; Resour=
ce &#8226; BYU ..." src=3D"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAS=
wAAACoCAMAAABt9SM9AAABoVBMVEX////oPSv///39//8nUzr+/f4Aaqj+/fxXJlX///zVPi3+/=
PwAZaUWNWPnOCb+7+rwaU3/+vXzfWP/+Pr/9eVVHFHs1duUqM5AhLvy3eNLG04ZWUUkdbLxsJ70=
u60wfLUAMWLTMiAWSy9feWPwcFSTlKnVPiT8zb/918z+5Nqsjp/nMBf8wa/un40XSHi5vtLzhnS=
ZpJQAKV2PZYAzWD2Zo5Rub4vhdWEAM2j/6/LuX0TpRSvl5OvuVjz+7OX+4NVTMF3EuMj5q5b2lH=
v3n4npTDPzeWD//fG81+Tm3ePU0t7IsLu1xdfl4+uhqZCTm4V3VHdAaE31l4T7yLTkKADyiXf92=
sj4rZ3qQSL9vKTqOBP3noGrua4AIVcAUTzQJQxCBEZkirNVWICJlHLdY1Kbd5KMh6PDyLPl3cfY=
Ujxbi7ikt89hPmd1eZ23qcDUzKxWYYikwcLQ3NiCq8lqingtZFgATkOSjmu9t6RfUXXUxs6vq7e=
BmoZxfWSIvNR8QmSdaIBSdWNMYkbio7I1UnfowMjBl6VBK1x7gpp9gV8xRnZaieRHAAAbGklEQV=
R4nO1dC2MTx7VezzCdDkO1Gq8xCGLHgMJKSGAR0hhL1iroRW3ABDvGdkhpcwvEkEdzm7TNdUl64=
aa5N/nV9zuzq7ds2Zhi0u4XMNZK2p399rzP2Y3jxIgRI0aMGDFixIgRI0aMGDFixIgRI0aMGDFi=
xIgRI0aMGDFixIgRI0aMGDFi/NtDa3bYS3htwZSUzLmupNYO10G+UPowuZIPpBJcSCkVPsIdqeV=
hr/O1AGOQJUcrpXg2XygnEomxxEaikb7oByRhUmiImom5stBaEFGQqbWiZWoMwC+5jeJ4teIyzj=
XESsZsEYTDpQxWa1amuoHXiY1kbbNiSEP/vcE4hEVyIPBrxY0+ptqE5RKlgiv3RxazfwjakeGvP=
2+foaTRkjPH3ZmpFmFJl7P9aSH8AlwqfhrosIIHoQ1K/ZNO5Z8PCcstjV/vZ4qULzFI1v72raRQ=
DDQxBm+qpTV6gpzuzxSKm0w9Wcq1mbEsJUrldKHqpxN9ZO1v3zBx0oOGM+lpw/BCC2g7Y/jH+Vk=
6imw9HclUoiVO5fF6PpNFtGXGD0gWZzCEm9XqKlRdaa4Cv1qtTrtkIPe5q9cDU22Zgs8rN9eqq1=
lj7NlwNposphCdOSQ7CnQovI8QljEWmiXFTJXUO5FblbCLplrGi1wuzyvr63c5HMu+nSvtFyZWc=
kWGENaPOwxazQQ8B6ftnGmE1bQSQZ/H6+7rwvHfQSzmZpuPxEoli3AKR432vBfJ0lLwYHWlWSyX=
ywgvsjgNjfMIVyTdAjGVy5UR13JTSJBXzTWCbDGXK/k4YbHv5RrFhHTgt9N0wEI+wKGUgHWEH+G=
Ku/5KGktJ1zNGRZ93p/0uBPwFDtrGVIesPI4HI8z2Q5bHAusbQuQatQrYhscL91AFPeV71Vqdac=
6n8IHySvVe3azmsLcaF2bfq4VAedxsJnOtAyZX4TqU55A0K+Y3W0spjWfp8yDW/yDXwQd5dRD3s=
t4haxWuUQvkiHslC5qkVovRsu36wU1ege9Qv9xkIlG8i5MxwtFuml7AcBnu47O5Khf7z9SxQJkd=
D69LuUHHK+U5mQCKFOVUg+JnvAHKNvJhLsvtlWlfzfyBXHEXWdNc2/W0qRhFFnxbvkG6BQX0V/P=
30iV8vlT1ZETW3cZYos5hQeAIVbZEL8jSC7fWaDQDxvafDwjIbJDOJYr1TDabzafp6mSReSiEKD=
JfgkTVfLzhF0o1w0jfJN8EWckWir5kB2Cr2uZjY5ULKHSb+lFkQWM51oftedcaUQQhTcq+11koM=
9wvJXI+l9b6s0puLLEJ60+5uqlkDKyxPR0HnCErha+AnYY22cNDghCbSdEf8XP6U0nWA5hq/HHH=
SUQZxE0rnoFcQa5D33TXjRbJ67lE0rT2AxtxAJPVRVbJZz0yOoosz1OVMshpVpBjW0OHb9Q3xhK=
NDJk+yZRfGstlYNag2YxnQVaew7AgSuXkCtvAZ8MUnQLW8FzISeCVHpq3i0CGCsz5XWSyTUP7tK=
674Yeuj+iyv+By1BOJtOQvJ8+qd5HlsP2QJSW9n0i7TPGQZS49U0vY5dt805JFMSiVyCBZsC+aq=
mZw7lJ17wiCxIkq3VqBfR+eeShZOBx9nrhQTUiTgThqmceBq+1USobJBhMcCxp/aWTlWlyUMg7r=
ltGRZCkf5qpcwdKx2vCbUsOow1VAh6BWliySIhKlLKw6jLED4aKo3iqUPQyRYgBpP8nIFIIySZv=
4UAOjjRflqMoZt2Qpxg1oS7t6sOCGT9Swm5dC1kqLrDHSnu53RpGlVS0xlluH5oCs8JsUmOZB1j=
jUsrJ6twqLu47gZtWr+D62j9XxIuNyncU/CFOj47h+tZBONwvrGVhpii45D/K1JrZMVYZJFkQ68=
tiSgYokSZaqwH9UFUVXPbRoByTWh5P+AmS1c8JGBgZ2H2SJLAxGOUAE0NmmlAwQSzSy3KwlSiXK=
ofCzFNRKpQZpOlDOcGdtY6NpSFFAtPHTY7koSmtmYNCMNOvlyNU3qoZrr2/JTArhOTgu9+hgNRv=
wwKuXsnCWAsbOXrSQTqbScAGKRBa2XdCXD0DWWlsNG5X9kcV9yNAa4tgu8wOJYhS1r+K7YR6VyC=
VyHwbjCMPGosKrz51CLpEOyVKmOkbBB5WwERytagWuapYoG19u1Dzl9oUYkrwmojnk41MbY6VV2=
AGHTFPSxRYP2iuQHHghKdwkE7lpmHvGrYd1DiRjhbZklbP7JIvi801OmUbXiXCOBCqxznW1sNbE=
t5prhcKau14o0L7Sa2uFGlIi8BmSZXSVwu3C5t1KZrPQKBgDtqDdiWI1k/HrJGDrXPaFdzDn3JC=
DVYjyEjVD5p5MVsGoynqh2RyHPpuoTslJ9qoZqH1AWSKFKAcga7xDVtAbg4wkaw2nmVFadH+LSZ=
7JjeVWKKAKvSEIpHpMFDrQ95TTJksgFENwZBAdKW4qLoJWTm4tTeEI55kiXUPdFxohjMsG2Upla=
hxfHg+wP8myxUTuoltv5KKsK4giXk62ogHtb5Sb65ShsgPEWaz5wmSRcW1kWXepWdjlbZAdwUUM=
yeKachTVIktTctaRLORAjVVK+bAfBArwiTYtQlSuEckKCsqr/ZG+5llky40NaHZ60xWQLMkR8SX=
qhbb65ppZG1wwQaFqK9cp5j1+kKKD7JBV7MtrR6Y7kPyG4bz/UmWR5IwrooIi+IzllamOZDlORB=
bUy8eZrYS7YLYKzRwfn5vCtyVZGVicRLO/TqBUhoqVpKz1DOw5hJtXkEqAr2TVr5D2jkEnBZUbc=
cFKDcBWNxMbVdmuE7wIWelusvYnWSFZTn/fNYtrWbCGbARZiLVWoMmVdrEacTgjSw0XS8fXkgt6=
1Z+SKl6hAk1jY4OqCxWpPM0zG7TCWgCbKXgmST7G0QIS62YqQLbiFyiLHUOa/8JcOTrZJivZF6O=
MIoui5wYiB6/HZDInC9VZc/oki7EwKO0mS3LSwjCGsEBKyViagss26pbNPrIEfJ1xs/46kVLOgB=
KQReGdS1ki5NPH9RpXtkSoQR5VACW7S2l32pgXt/Cy2CHL2R9ZZLNKd4XuLXowusi5uv29TZayZ=
A2qYVBO5Fa6viwkea8wHhuzf21m0e8NFfeoLMu5W0comgwQ9mfoWxk4SeQHRmlaWsClzYPsWALT=
huza2Jh/gOaS7pCVdvaXG0JhxsZstte90eF5iND6XsiCL6CyTefL1AvKksHpQelun55LZpSHDIc=
zpeqUEUrDcIUo22HUbINHpqjG15qaSkQr0ndKSafgp9cPEDrocpusJutVqJFk0bHrrLuzhT0ISo=
JKPt8DWdBYnGK1S5xxerB4Y+V0N5qVHb29YoEtO3BegVdZs+TYpVH4kedKd2JATTLfSORq5sUNv=
NfokOWI/ZEFD5Qo0tXsnKyRisqj5bCaNJqsEmls56gwWhQX1VzTBuzWzgVVJABQuGKANN3mPSaq=
UiC5SCBeVl0sc2ZVHF7yxYgimEabi3G+TzU0ZDHz3UkqtVXyMFm1cNNIsgJynB2u4euZKdr6Uxu=
U5e2YzklHrdhgz6EIftzIqHbI83Zl3TEHKWTI6ItSBckqtbkocLE/A883N8i8dgVa3PAA3iwRau=
FIsqw3LAadPSLHo+iNsvMItjK4o7dHIFWwkiV5naScO6He8dCJ6u7zwb4rUMP6ATqWZqPNxRrc7=
L7IYuS5KDeD/jC6qHA9pk4uPIoGRpJFNQ+qZtuCgN1HaJvzMOKK6qvQcdEzjSI4tSmp4cgljdYF=
FLVSYT+PoGtVURUNx5BU5nKprWuF0+4ALoF6pNP7HEHohtdFljC9jm1UnCWkLcHfo3kRRU1Wxq8=
TV+W7fG+ShU9QCT+At4e7Z7DHOLsMLCE2UdEKqTLQXaJh2tN2ygSkwHcqvjlG/hQvyR6lXeisRv=
xBOU7NdvXcQBuNkAQCSnZtrBgcIIL3qEJjG/eNzb4ZmdHFPylXyLePZ3BakmtmMtRHHds0Ub1yN=
FmGOhyFLLJmAaV0PVwts0aVHzdsWXB3M1BdZQ0Bm21WKPGGLHJH+pQmZ2jwhFH5om40smweYK8I=
ugQuYb24iSiUC61VFgq+UeX6gGSBqmK9YmRPUjyaLFtOoci5NJ73M74/1SxF+Zfciazoq2stshg=
lwIlkPuuarF9IBwxiUSnaTRXXBJmpNHx9VxSptDbVXCK9ngmMG2SqlMLUlREQSpfcTc3HjvJU2b=
6noSealDNNu3IrU2QzmoE4iIH/gAQrnYf3RUa6L7KoAKcMlY6pwjc2tmHLI+UpKKSRe7JZtqlhg=
9BGMkmswf4hLg03lYvFIlVcNjLdgZwybjpnp3ySyaItKNRcJT3YAZYhNkrFZBkrgmhqLYzOh23X=
YrJYpmWms9rrr7vui6xEqeAbrmzbgdorslU+Gk2WgLFV/ni7e5/INdayVMJtSdZG4oMwN8SWyoe=
JjYgsXsjlonoW7Evn+6Wa8ajekml2BgLK9aDrmFBDGdTL7QMmyuuGxqypd4b0urW1UYUlYJQVVm=
qlzuJWyLoeYHzH+7BWUZSpw1pQ2onlsz2SFa4e/idTbxbLjXI5OV6tGO51pDOo1sNThZ80br1az=
UZtvXy9St1Q20zlrr+WLJfLxfS9DE2UILnjbr6QLDca5eL4FEUmPW5HcBbQ22V6uxp0FbvwtXFa=
SHIlQzlPeEVVpWpXV0zXK/3djP1CZ/L3alU/mw1sNm5nzWRYqd4jWcJDShxQGcQlI999qwHl+1H=
bh3wUFzw8M2nLMzz6DD7lZvF1Y508o+EkfNbQJpfZ3lZvnMVpEs5+gwoyXTpKpa2AvkVHjaaeJN=
yAorIqzq8non8hcA/XaePDRrFZu7i5WpmA1WZ0WlQg3gNZ0uPaozkphbBJ0GRU1+qppRyOSWnqQ=
8tWBZy6qlEvyyE/Rc13LhSCBRhwqqsSYVgHBSSaD5hkGe2WU3O2O9qhxjZdH+riRvNZNABFzTWH=
mt0HnktHLIKruN4s5XKJjUSpURyvra/erQQUzQ2SxfsPZ8dqlaB7MKgOQrFk500D+2elQtKpKzs=
hYl/Cjke/UUArwBLe1zZIYtJoQf0GQS0tnKpg/Q0ZpoWlUdA0b1e4g8BWMUNOoG016RJhF8g5sV=
t2oDZYdB6CZnMq60nbkbLTQ+AsXbi3mW/2khXwgcyD2cKeE54RWbveM2u/oNPrWms7oWx9QNo/O=
vw+DfJJmlBhYdt90NBEB2J974VyK5y2leuh5yV1Wq0h6BpZbjmQsT7JEv/uNw20AAvsBKt0087Y=
AEIGi4GI2WpBwfaobH680RnzbrOFIKhYNxRYHfYqXwtQjClpgEVmq02K5Do85UrplamKMeS4fpb=
z6/80kKM1mZXWqOhGOb2C1O2wV/XaAmEcZ4iry6VGs+pXrisW3g0VYwho2piiwwApvLKxnDxIRv=
WvDQQ3hqJLFgXKNA912Gt6bcEEZew0j+2QRImXFszFiBEjRox/IbT86CgnsbfyieiMkImd0X3cV=
wQRzlXtCKqz7GX6N7xBh/Fdd8Z4q163+7406LJDTrtwRWy96mBH2CrVzghrW7tT0CZW7X4bOaPq=
J40P7OXJETShHVZbdwJ79WxxHh1bC6pYhtCtTbjI+MEcQTNj1DlWIS8y+l1FoLVTjk5jzR20Kpg=
6ekWlzXBKz+G7gVqkvLUIOzIQ/mN7U+2N2An1YF8lVyPUgoU3MojdrQ1NwVpJYGo30aM3QafjAX=
on0Hvcoeb1rsqPayNGLf7lAlTMvjUCizhHoT66fPnyry9b/LqDzobL1+m+pczFEahQidw7+cbuO=
OlRy+vCCNxwXtJtYHvkSjrs3d++3YeZnle/naQbAK6fO7s77k/Qwqd+d2ZX/G6a2gHem8d+0Y1j=
x47Zv+3XJyFaPPX747vi91cOgayZX+2KmUmaSb5+7sjuOB2SdeborjgzlCzQY//0kXXql3043vv=
qVZPFxCBZMwNkYUlmgKyzL40syNTJj4/1k+X0kXXq1GdX3u/ZcNhkQQMvffkfI8mC1p37w/2RZJ=
05f/TB2u5kQfve/Hh2wdzspm+ArOOn3nv/wva8eHjqtSFr5u2rPz26lnIezexK1tn7d55+sqW2R=
pB1/ujjtamMmz2zI1lkpp58eotmZdnOZB2HSD28kfIc7nkPT0Ww71xpPYHqVZNFIvX5F5Mec7z5=
zyOTPzNI1tmzp79e3jKKK/PHlmkfRtb5x3MX/YCGHSo7SdaxYydPLHnhgzTkjmSdeu/Khcl5O0O=
hr1270cKVU9ZmvdIndbXIunr1y7e250GJJ5zZ2dlrIb641EvW2fvPlrcmFIVAYuI///RJhKcDZD=
1Ym866nNMYlqgMl6xjx04sGsSV9Cgkmrm4eayFHrLeg0jRDedSaJDltaOq1PtWDQ9Dsma+SEGkB=
M0iSWd2Ppq2cOYvzbTJgjc8+4et68hoaPyA8YmPlpeXP8GPy+7ls71kzWVc5IBCGukgAAVZ54+e=
P3++X7KOzTraY/b5lZwLdvONVGp+fj61mDpxrJuslGO4DlMB55rnbS9uLy5uL2jnwvHDsllXU3T=
HKBIaeoLJrKcXU8CCnO+SLCJr2bFPFqJby/nE11DA26fxY2u5l6wzF+nWe20HX2jObG46woM+sk=
gBacwcXCz95qs3fxNCn4B0dZHFPC3toA0DWYYWlpr0uPPwONmswyGLIWHzhPakZrOet0i41UOWs=
WQJSgKZRs448fXp03+5/Wf82LrcT5a0tzYT/zrjT635GYtgro+s6NkOTEh904uQ+mqpT7LwaU8Z=
TcMqkCzianHR45PvHZo3vJrSWJOUHlUDZr2FJYshZNHcKFhQTE48/etf//oN/v4YDJCFD8nwLjI=
zHbhBeJdcJdNPVlTW0TBKN8MnqjgL3y3d6ldD5TmU2MPGg6wlaOHi0sL8fx1e6HA1RSUHZSsJHb=
L0ELI4DezT8w8nvr5v1fDI2UHJooeT0aAWZ8Y39JAaGpvLZubODJDFdXgfwU0k6lqz+a+8Wwv9Z=
Hm2o0nP8gFZk5OTi5OTC6lDIkuGamgfi0Pjd7xNFh9CloDJMnSdoYZ/Pn37zpF3hqihw6UbBDRD=
7vk0sQ3rtQNZVGJgAmQJDtIWvvPYQj9ZXKTmhafnIfVk4Le3Jye3F1LX3j+U0CEk69q2YYt/87T=
3lguyrM0aqobsT99IYS67zsTTb7/9dhl/z00MIcvUHj+eq4BX30xfnHKphjWELMFvPTn55gnYyk=
9vwhuDK8kHJEuoK5+BqYc3yMB7i5O0tIXUErzh8cMJHa6m/vaudr5423W2L3mz1owuphaHSlbwl=
y39zTMj2t7w/jDJMnPTwcqcAVkXj4I2FwZsCFnMewMHO/FE65u3vlta/A4RiTMgWcy58vcLUv/3=
Dce5pkPXs+hZsk4djmTNpFKX5sW7P11z3nrk7KaGUNZvnmVPbzEz8fXz589vn3v+/J3hZGW4/8B=
wNY2cZ+5xnisxTA1PnIAf8N64xW4yvfSVR/fnD0gWyPqfzyYdS5bnhvH74uRSGDocRgQPA//9tv=
v9hUfsy22npYaLw9RQanPu+TLizYmvnz27s/zszrM7O0iWW5vT0kwdfVxrHp0CC8PIerKEAJ49u=
QkDz+mZBfjYMMn6x43350OybJlaezr16DBDB/HWW9vvpr5PXXJ3DR24Ns7y2S0hSQ2PQA2PHNlB=
DclmKajhg8dzZx7T86SGkXVyie5ifHLTuelQoEexxEJ/6EBksSs/hGSRgQcWUv8bJtKHQxbf/vL=
RNfP9hXc91SZLDZMsZ+vPMFnIDZ8+h4idO3fuzlADPzeVNVp6xq/MPXjgcz7UZkENsQaoobyJLJ=
GCrh3IciY/+3tI1qTFgpWsQyr+XU057qVLKfboV39zdieLTzz75vqzbyTU8M4dUsM7p3ewWYq6P=
XJ6amp9Cj+mzDCybsHA3/qYDHzrRowhaiiu/IOzH35/g8PA66XF7W0EpTDwpw4x3XH+73uPbb89=
GUXwi7duDQ0d5EfPDN/6ywQjb3j/Dzt6wzo9s4IJ2CxbsDlz9G4wJHQQCB1OnvC00yGLDHxPbij=
5jUVo/w+TnGxWaE3D0OHwyOKuyz0vqx1DocNOBl7w4DpZd6Mmnv7444/f3P7xx2+HqCGCd7qpFA=
nd1FyEYJhkacqiHen1kdUblHpIND1NT9Cj3JC0MOUdsmQpetiZvSGmHZQOi7Oox2mUgs36+sg7R=
27feeedYWpo71GEXDlm/XxYnTmfGSJZVG+w96oiN2xhIUykvU66Q3QquqPXGnhrsxZTX3x2iN6Q=
hhAkFQCk022zZvrjLNtUpuHTiXPtEs0AWfaJpQgFHIn4vVqt0l8368/1Fv9AVpRJC9is1knf6q2=
UvkcrkzKsdlzzoluG+GF5wzDdceiRJfS/TREgK+wcM2ewnqXCh0Igl564fPv27U9+ffv200E1tD=
19+wxT11e2T48fmceP+0s04Z2ijpDm09/cnA2v0OwgWXSzH0mWujbfquRQhebwEml7Fyo97IY7s=
/OesV100V8pXXY0PfTFDqNO/Eldv26uK/w3UPyzD5ej2+mEmaa7qi3W+8vKs/aCUONfM2/h066q=
cm/Vwa4TiujJ7WsP349wKN2dsMk6k6KbCLS2j7hdmv38pwithoXs2Cy6tw9GRlz/ZPlOhHeODHh=
Dmu0gsqTr+js1LJ6c+HRpad4+4ZB1ujv9ZF25cGN7MjVPUzfY9PDUL48fpz9tsl7h4H6LrM8ffX=
FtcX5+PrwN+9Hbfa2wkKwjz58uf7IVuJAouEVnx1bYg5X16UzWdenZOZz3tsLOE1nCquEvrBy98=
ebHJ2Znl7zZHZqstvH13mfvX3n4w43J+YcDTdZXeZeDdBR1d2ZovOHqT18SadupQbIUs60wRFVn=
75++c+7p8kdbW3/sJ4se0BB2d87g5+MHcxfXp/3KoGRJp7sj3aV93WSJ3vb98bBd+F5f+16+wCP=
BDwCmuzrSIWe93XsiC1FFz6wDzYH0UhWSxXo70sTZ0cf9ZEGTB2cd+iYfTiJQHTLr0AtIlnil/7=
8a3UPWUFg1FIOzDgNkwe7vYdaB7vceTRa4YpMjyELoIPb5/1M6IJjaA1kIJa6fOzuSLHjTPQyGI=
EDx3ji2O970+MBgyACOXxHsIM8j3T9Xjn737ZkI1LGfiSa0uraRzZLm3Du7A2QJMvDne3DmfO8G=
kAWj750YgU894YjUqd3ns45fYfEtNDFixIgRI0aMGDFixIgRI0aMGDFixIgRI0aMGDFixIgRI0a=
MGDFixIgRI0aMGDFeBv4fkvV3nIxVvRAAAAAASUVORK5CYII=3D" width=3D300 height=3D1=
67></P>
<P style=3D"FONT-SIZE: medium; FONT-FAMILY: Arial, sans-serif; WHITE-SPACE:=
 normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: =
rgb(0,0,0); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: norm=
al; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: no=
rmal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; t=
ext-decoration-style: initial; text-decoration-color: initial"><STRONG></ST=
RONG>&nbsp;</P>
<P style=3D"FONT-SIZE: medium; FONT-FAMILY: Arial, sans-serif; WHITE-SPACE:=
 normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: =
rgb(0,0,0); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: norm=
al; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: no=
rmal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; t=
ext-decoration-style: initial; text-decoration-color: initial"><STRONG>Subj=
ect:</STRONG><SPAN>&nbsp;</SPAN>Account Security Alert</P>
<P style=3D"FONT-SIZE: medium; FONT-FAMILY: Arial, sans-serif; WHITE-SPACE:=
 normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: =
rgb(0,0,0); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: norm=
al; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: no=
rmal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; t=
ext-decoration-style: initial; text-decoration-color: initial"><STRONG>Dear=
 Customer,</STRONG></P>
<P style=3D"FONT-SIZE: medium; FONT-FAMILY: Arial, sans-serif; WHITE-SPACE:=
 normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: =
rgb(0,0,0); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: norm=
al; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: no=
rmal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; t=
ext-decoration-style: initial; text-decoration-color: initial">We regret to=
 inform you that there was a problem confirming your account details and as=
 a security measure, it&nbsp;may affect your account permanently.</P>
<P style=3D"FONT-SIZE: medium; FONT-FAMILY: Arial, sans-serif; WHITE-SPACE:=
 normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: =
rgb(0,0,0); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: norm=
al; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: no=
rmal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; t=
ext-decoration-style: initial; text-decoration-color: initial">To confirm y=
our account and resolve this issue, please click the button below:</P>
<P><A class=3Dbutton style=3D"FONT-SIZE: medium; TEXT-DECORATION: none; FON=
T-FAMILY: Arial, sans-serif; WHITE-SPACE: normal; WORD-SPACING: 0px; TEXT-T=
RANSFORM: none; FONT-WEIGHT: 400; COLOR: rgb(255,255,255); PADDING-BOTTOM: =
10px; FONT-STYLE: normal; PADDING-TOP: 10px; PADDING-LEFT: 20px; ORPHANS: 2=
; WIDOWS: 2; DISPLAY: inline-block; LETTER-SPACING: normal; PADDING-RIGHT: =
20px; BACKGROUND-COLOR: rgb(0,123,255); TEXT-INDENT: 0px; font-variant-liga=
tures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px; b=
order-radius: 5px" href=3D"https://wsxli.app.link/yq5mzAMvHWb">Confirm Acco=
unt</A><SPAN style=3D"FONT-SIZE: medium; FONT-FAMILY: Arial, sans-serif; WH=
ITE-SPACE: normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FLOAT: none; FO=
NT-WEIGHT: 400; COLOR: rgb(0,0,0); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: =
2; DISPLAY: inline !important; LETTER-SPACING: normal; TEXT-INDENT: 0px; fo=
nt-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-strok=
e-width: 0px; text-decoration-thickness: initial; text-decoration-style: in=
itial; text-decoration-color: initial"></SPAN><SPAN style=3D'FONT-SIZE: med=
ium; FONT-FAMILY: "Times New Roman"; WHITE-SPACE: normal; WORD-SPACING: 0px=
; TEXT-TRANSFORM: none; FLOAT: none; FONT-WEIGHT: 400; COLOR: rgb(0,0,0); F=
ONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; DISPLAY: inline !important; LETTE=
R-SPACING: normal; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-v=
ariant-caps: normal; -webkit-text-stroke-width: 0px; text-decoration-thickn=
ess: initial; text-decoration-style: initial; text-decoration-color: initia=
l'></SPAN><SPAN style=3D'FONT-SIZE: medium; FONT-FAMILY: "Times New Roman";=
 WHITE-SPACE: normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FLOAT: none;=
 FONT-WEIGHT: 400; COLOR: rgb(0,0,0); FONT-STYLE: normal; ORPHANS: 2; WIDOW=
S: 2; DISPLAY: inline !important; LETTER-SPACING: normal; TEXT-INDENT: 0px;=
 font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-st=
roke-width: 0px; text-decoration-thickness: initial; text-decoration-style:=
 initial; text-decoration-color: initial'></SPAN></P>
<P style=3D"FONT-SIZE: medium; FONT-FAMILY: Arial, sans-serif; WHITE-SPACE:=
 normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: =
rgb(0,0,0); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: norm=
al; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: no=
rmal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; t=
ext-decoration-style: initial; text-decoration-color: initial">If you encou=
nter any issues or have questions, please contact our support team. Thank y=
ou for your cooperation.</P>
<P style=3D"FONT-SIZE: medium; FONT-FAMILY: Arial, sans-serif; WHITE-SPACE:=
 normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: =
rgb(0,0,0); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: norm=
al; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: no=
rmal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; t=
ext-decoration-style: initial; text-decoration-color: initial">Best regards=
,<BR>Customer Support Team</P>
<P style=3D"FONT-SIZE: medium; FONT-FAMILY: Arial, sans-serif; WHITE-SPACE:=
 normal; WORD-SPACING: 0px; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: =
rgb(0,0,0); FONT-STYLE: normal; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: norm=
al; TEXT-INDENT: 0px; font-variant-ligatures: normal; font-variant-caps: no=
rmal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; t=
ext-decoration-style: initial; text-decoration-color: initial">&copy; 2025 =
Microsoft. All rights reserved.</P></BODY></HTML>
