Return-Path: <bounce+h8-minsk=oriontv.net@email.prom.ua>
Received: from m45.esputnik.com (52.50.69.120) by satipe.disaki.es for <minsk@oriontv.net>; Wed, 17 Sep 2025 16:45:54 +0200 (envelope-from <bounce+h8-minsk=oriontv.net@email.prom.ua>)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; s=key1; d=email.prom.ua;
 h=X-Mailer:Date:From:Reply-To:To:Message-ID:Subject:MIME-Version:Content-Type:
 Feedback-ID:List-Unsubscribe:List-Id:X-ES-IID; t=1758120354; x=1758121554;
 bh=8+Lq5tuQMS2T7ZInEJgAcToEDeFzwmV/eJ1b35JoC6M=;
 b=R2qDvacjyovYT6Q9WRDogsU10jYCKfgxZSXrZcvz6IQkvdKXD9Gc6pHMKdmohI3mIffzG7mJj2vK
   aV54UFMdyLg2F3WQ9Qdsaj5RiOejY+l29acBwfhAP3npqWw5qUcHktwyzNbISgzR3Nuvzsfnq4io
   oKmZNezWG+VPQKccB+s=
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; s=km2; d=esputnik.com;
 h=X-Mailer:Date:From:Reply-To:To:Message-ID:Subject:MIME-Version:Content-Type:
 Feedback-ID:List-Unsubscribe:List-Id:X-ES-IID; t=1758120354; x=1758121554;
 bh=8+Lq5tuQMS2T7ZInEJgAcToEDeFzwmV/eJ1b35JoC6M=;
 b=Omced1TMkqNcy00yin6HVTgAC3ZFbP2Hx0RUhDRCJETbvfD0uGnsi/07oH6uWQ0kHcmljxMxF36Y
   xO5ytMjwUqrdYh9Ob1XFn/VF0P/7B2L1oOIZBll9p9UjVOqceVuR5ursFmUZ5NdxavOJTsgRHflG
   u2cxyRbpWkCED/J4PQf7x/Pi+FxHWu5p0rPRDHBu1baFYdHTvKkmyFFCOMQLtv+pgE+SV/yIZTac
   kFrqORPfo0l/nioXUpYCesrhT7+5wgqAYwifzZODZCb04D0f4ZTH96QVYlhDbAkqHoznWCS42PHf
   6spuRx0uqmCeaues/N82rChKcsetNoxuNMOPvA==
X-Mailer: eSputnik.com Mailer (3)
Date: Wed, 17 Sep 2025 14:45:53 +0000 (UTC)
From: "Prom.ua" <newsletter@email.prom.ua>
Reply-To: "Prom.ua" <newsletter@email.prom.ua>
To: minsk@oriontv.net
Message-ID: <01c65e60-93d5-11f0-85c7-195e1bea4e72@ms4-7fb44bf789-n4gm6>
Subject: =?UTF-8?B?8J+Gk9CR0LXQt9C60L7RiNGC0L7QstC90LAg0LTQvtGB0YLQsNCy0LrQsCA=?=
 =?UTF-8?B?0Lcg0L/RltC00L/QuNGB0LrQvtGOIMKr0JTQu9GPINGB0LLQvtGX0YXCuw==?=
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_1450349_1419197779.1758120353761"
X-Mailru-Msgtype: o6798
Feedback-ID: t262256:6798:trigger:eSputnik.com
X-Report-Abuse-To: abuse@trap.esputnik.com
X-Complaints-To: complain@trap.esputnik.com
X-Priority: 1
List-Unsubscribe-Post: List-Unsubscribe=One-Click
List-Unsubscribe: <https://esputnik.com/message-service/v1/unsubscribe/01c65e60-93d5-11f0-85c7-195e1bea4e72>,
 <mailto:complain@mta1.esputnik.com?subject=unsubscribe-01c65e60-93d5-11f0-85c7-195e1bea4e72>
List-Id: <6798.trigger>
X-Report-Abuse: Please report abuse here: abuse@trap.esputnik.com
X-ES-IID: 01c65e60-93d5-11f0-85c7-195e1bea4e72

------=_Part_1450349_1419197779.1758120353761
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

0JXQutC+0L3QvtC8INC90LAg0LTQvtGB0YLQsNCy0YbRluKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82P
IOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKAh82PIOKA
h82PIOKAh82PIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKt
IMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKt
IMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKt
IMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKt
IMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKt
IMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKt
IMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKt
IMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKt
IMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKt
IMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKt
IMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKt
IMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKtIMKg
CtCf0LXRgNC10LPQu9GP0L3Rg9GC0Lgg0LvQuNGB0YIg0YMg0LHRgNCw0YPQt9C10YDRliBbIGh0
dHBzOi8vZXNwdXRuaWsuY29tL3ZpZXdJbkJyb3dzZXIgXQogWyBodHRwczovL3Byb20udWEvdWEv
IF0KIFsgaHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL3Byb20udWEgXSBbIGh0dHBzOi8vd3d3Lmlu
c3RhZ3JhbS5jb20vcHJvbS5wb21wb20vIF0K0JfQsNGA0LDQtyDQutGD0L/Rg9GO0YLRjCBbIGh0
dHBzOi8vcHJvbS51YS91YS9TZWFzb24tZmVlZCBd0JTQvtC00LDRgtC+0LogUHJvbSBbIGh0dHBz
Oi8vYXBwLmFkanVzdC5jb20vMWxvdWJ4MW0gXdCf0YDQvtC8LdC+0L/Qu9Cw0YLQsCBbIGh0dHBz
Oi8vcHJvbS51YS91YS9zYy9wcm9tLW9wbGF0YSBdCtCR0LXQt9C60L7RiNGC0L7QstC90LAg0LTQ
vtGB0YLQsNCy0LrQsArQntGE0L7RgNC80LvRjtC5INC/0ZbQtNC/0LjRgdC60YMgwqvQlNC70Y8g
0YHQstC+0ZfRhcK7INC30LAgMzAg0LPRgNC9L9C80ZbRgSDRgtCwINC+0YLRgNC40LzRg9C5INCx
0LXQt9C60L7RiNGC0L7QstC90YMg0LTQvtGB0YLQsNCy0LrRgyDQtNC+INCd0L7QstC+0Zcg0L/Q
vtGI0YLQuCDRgtCwINC80LDQs9Cw0LfQuNC90ZbQsiBSb3pldGthLgrQmtGD0L/Rg9C5INCy0LjQ
s9GW0LTQvdC+INC90LAg0J/RgNC+0LzRliAtINCx0LXQt9C60L7RiNGC0L7QstC90LAg0LTQvtGB
0YLQsNCy0LrQsCDQstC20LUg0YfQtdC60LDRlCDQvdCwINGC0LXQsdC1ISDwn5iJCiBbIGh0dHBz
Oi8vbXkucHJvbS51YS91YS9jYWJpbmV0L3VzZXIvc3Vic2NyaXB0aW9uIF0KIFsgaHR0cHM6Ly9t
eS5wcm9tLnVhL3VhL2NhYmluZXQvdXNlci9zdWJzY3JpcHRpb24gXQoq0JTQviAzMSDQu9C40L/Q
vdGPIDIwMjUg0YDQvtC60YMg0LLQutC70Y7Rh9C90L4g0L/RltC00L/QuNGB0LrQsCDQtNGW0ZQg
0LLRltC0IDEwMCDQs9GA0L0sINC00LDQu9GWIC0g0LLRltC0IDQwMCDQs9GA0L0uwqAg0JTQtdGC
0LDQu9GM0L3RltGI0LUgWyBodHRwczovL2hlbHAucHJvbS51YS9oYy91ay9hcnRpY2xlcy85NzMy
NjkwMzg2NTg5IF0K0J7RhNC+0YDQvNC40YLQuCDQv9GW0LTQv9C40YHQutGDIFsgaHR0cHM6Ly9t
eS5wcm9tLnVhL3VhL2NhYmluZXQvdXNlci9zdWJzY3JpcHRpb24gXQogWyBodHRwczovL2FwcC5h
ZGp1c3QuY29tLzFsb3VieDFtIF0K0JLQuCDQvtGC0YDQuNC80LDQu9C4INGG0Y4g0YDQvtC30YHQ
uNC70LrRgywg0L7RgdC60ZbQu9GM0LrQuCDRgNC10ZTRgdGC0YDRg9Cy0LDQu9C40YHRjyDQvdCw
IHByb20udWEgWyBodHRwczovL3d3dy5wcm9tLnVhIF0K0JLRltC00L/QuNGB0LDRgtC40YHRjyDQ
stGW0LQg0YDQvtC30YHQuNC70LrQuCBbIGh0dHBzOi8vZXNwdXRuaWsuY29tL3Vuc3Vic2NyaWJl
IF0K
------=_Part_1450349_1419197779.1758120353761
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns=3D"http://www.w3.=
org/1999/xhtml" xmlns:o=3D"urn:schemas-microsoft-com:office:office" lang=3D=
"und" style=3D"font-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, A=
rial, Ubuntu, sans-serif"><head> <meta charset=3D"UTF-8"> <meta name=3D"x-a=
pple-disable-message-reformatting"> <meta http-equiv=3D"X-UA-Compatible" co=
ntent=3D"IE=3Dedge"> <meta content=3D"telephone=3Dno" name=3D"format-detect=
ion"> <title></title><!--[if (mso 16)]><style type=3D"text/css">
    a {text-decoration: none;}
    </style><![endif]--><!--[if gte mso 9]><style>sup { font-size: 100% !im=
portant; }</style><![endif]--><!--[if gte mso 9]><noscript> <xml> <o:Office=
DocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPe=
rInch> </o:OfficeDocumentSettings> </xml> </noscript><![endif]--><!--[if ms=
o]><xml> <w:WordDocument xmlns:w=3D"urn:schemas-microsoft-com:office:word">=
 <w:DontUseAdvancedTypographyReadingMail></w:DontUseAdvancedTypographyReadi=
ngMail> </w:WordDocument> </xml><![endif]--><!--[if !mso]><!-- --> <link hr=
ef=3D"https://fonts.googleapis.com/css?family=3DMontserrat:500,700,800&amp;=
display=3Dswap&amp;subset=3Dcyrillic-ext" rel=3D"stylesheet"><!--<![endif]-=
-> <style type=3D"text/css">
#outlook a {
=09padding:0;
}
.es-button {
=09mso-style-priority:100!important;
=09text-decoration:none!important;
}
a[x-apple-data-detectors] {
=09color:inherit!important;
=09text-decoration:none!important;
=09font-size:inherit!important;
=09font-family:inherit!important;
=09font-weight:inherit!important;
=09line-height:inherit!important;
}
.es-desk-hidden {
=09display:none;
=09float:left;
=09overflow:hidden;
=09width:0;
=09max-height:0;
=09line-height:0;
=09mso-hide:all;
}
.es-button-border:hover a.es-button, .es-button-border:hover button.es-butt=
on {
=09background:#EDD8FF!important;
=09color:#333333!important;
}
.es-button-border:hover {
=09border-color:#42d159 #42d159 #42d159 #42d159!important;
=09background:#EDD8FF!important;
}
td .es-button-border:hover a.es-button-1653046069594 {
=09color:#01011B!important;
}
@media screen and (max-width:384px) {.mail-message-content { width:414px!im=
portant } }
</style> <style> #mshidden { mso-hide: all; display: none; width: 0px; heig=
ht: 0px; float: none; opacity: 0.0; border: 0px solid; margin: 0px;} </styl=
e><link rel=3D"shortcut icon" href=3D"https://pics.esputnik.com/repository/=
home/6798/common/images/favicon.ico"></head> <body style=3D"width:100%;font=
-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-=
serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Mar=
gin:0"><span style=3D"display:none !important;font-size:0px;line-height:0;c=
olor:#ffffff;visibility:hidden;opacity:0;height:0;width:0;mso-hide:all">=D0=
=95=D0=BA=D0=BE=D0=BD=D0=BE=D0=BC =D0=BD=D0=B0 =D0=B4=D0=BE=D1=81=D1=82=D0=
=B0=D0=B2=D1=86=D1=96=E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=
=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =
=E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=
=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=
=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=
=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=
=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =
=E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=
=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=
=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=
=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=
=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =
=E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=
=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=
=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=
=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=
=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =
=E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=
=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=
=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=
=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=
=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =
=E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=
=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=
=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=
=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=
=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =
=E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=
=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=
=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=
=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=
=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =
=E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=
=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=
=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=
=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=
=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =
=E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=
=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=
=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=
=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=
=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =
=E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=
=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=
=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=
=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=
=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =
=E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=
=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =E2=80=87=CD=8F =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=
=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =C2=AD =
=C2=AD =C2=AD =C2=AD &nbsp;</span><img id=3D"mshidden" src=3D"https://esput=
nik.com/repository/applications/commons/hidden.png?iid=3D01c65e60-93d5-11f0=
-85c7-195e1bea4e72" alt=3D"" style=3D"display: block; width: 0px; height: 0=
px; visibility:hidden; float: none; opacity:0.0; filter:alpha(opacity=3D0);=
border: 0px solid; margin: 0px"> <div lang=3D"und" style=3D"background-colo=
r:#F4F4F9"><!--[if gte mso 9]><v:background xmlns:v=3D"urn:schemas-microsof=
t-com:vml" fill=3D"t"> <v:fill type=3D"tile" color=3D"#f4f4f9"></v:fill> </=
v:background><![endif]--> <table width=3D"100%" cellspacing=3D"0" cellpaddi=
ng=3D"0" role=3D"none" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;b=
order-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;he=
ight:100%;background-repeat:repeat;background-position:center top;backgroun=
d-color:#F4F4F9"> <tr height=3D"0"> <td style=3D"padding:0;Margin:0"> <tabl=
e cellpadding=3D"0" cellspacing=3D"0" border=3D"0" align=3D"center" role=3D=
"none" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:c=
ollapse;border-spacing:0px;width:600px"> <tr> <td cellpadding=3D"0" cellspa=
cing=3D"0" border=3D"0" height=3D"0" style=3D"padding:0;Margin:0;line-heigh=
t:1px;min-width:600px"><img src=3D"https://npgona.stripocdn.email/content/g=
uids/CABINET_837dc1d79e3a5eca5eb1609bfe9fd374/images/41521605538834349.png"=
 width=3D"600" height=3D"1" style=3D"display:block;border:0;outline:none;te=
xt-decoration:none;-ms-interpolation-mode:bicubic;max-height:0px;min-height=
:0px;min-width:600px;width:600px" alt=3D""></td> </tr> </table></td> </tr> =
<tr> <td valign=3D"top" style=3D"padding:0;Margin:0"> <table cellpadding=3D=
"0" cellspacing=3D"0" align=3D"center" role=3D"none" style=3D"mso-table-lsp=
ace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;ta=
ble-layout:fixed !important;width:100%;background-color:transparent;backgro=
und-repeat:repeat;background-position:center top"> <tr> <td align=3D"center=
" style=3D"padding:0;Margin:0"> <table cellspacing=3D"0" cellpadding=3D"0" =
align=3D"center" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-=
collapse:collapse;border-spacing:0px;background-color:transparent;width:600=
px" role=3D"none"> <tr> <td align=3D"left" style=3D"padding:0;Margin:0"> <t=
able cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"none" style=
=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;bord=
er-spacing:0px"> <tr> <td align=3D"left" style=3D"padding:0;Margin:0;paddin=
g-top:10px;padding-bottom:10px"> <table cellpadding=3D"0" cellspacing=3D"0"=
 width=3D"100%" role=3D"none" style=3D"mso-table-lspace:0pt;mso-table-rspac=
e:0pt;border-collapse:collapse;border-spacing:0px"> <tr> <td align=3D"cente=
r" valign=3D"top" style=3D"padding:0;Margin:0;width:600px"> <table cellpadd=
ing=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"presentation" style=3D"m=
so-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-sp=
acing:0px"> <tr> <td align=3D"right" style=3D"padding:0;Margin:0"><p style=
=3D"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-li=
ne-height-rule:exactly;font-family:Montserrat, 'Google Sans', 'Segoe UI', R=
oboto, Arial, Ubuntu, sans-serif;line-height:21px;color:#333333;font-size:1=
4px"><a href=3D"https://promaaua.esclick.me/1kPyBWwihVgPsitcOj" target=3D"_=
blank" style=3D"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso=
-line-height-rule:exactly;text-decoration:underline;color:#8b08f9;font-size=
:14px">=D0=9F=D0=B5=D1=80=D0=B5=D0=B3=D0=BB=D1=8F=D0=BD=D1=83=D1=82=D0=B8 =
=D0=BB=D0=B8=D1=81=D1=82 =D1=83 =D0=B1=D1=80=D0=B0=D1=83=D0=B7=D0=B5=D1=80=
=D1=96</a></p></td> </tr> </table></td> </tr> </table></td> </tr> </table><=
/td> </tr> <tr> <td align=3D"left" bgcolor=3D"#ffffff" style=3D"padding:0;M=
argin:0;padding-top:15px;padding-bottom:15px;padding-right:20px;background-=
color:#ffffff;border-radius:16px 16px 0px 0px"> <table cellpadding=3D"0" ce=
llspacing=3D"0" role=3D"none" style=3D"mso-table-lspace:0pt;mso-table-rspac=
e:0pt;border-collapse:collapse;border-spacing:0px;width:580px"> <tr> <td va=
lign=3D"top" style=3D"padding:0;Margin:0"> <table cellspacing=3D"0" cellpad=
ding=3D"0" align=3D"left" role=3D"none" style=3D"mso-table-lspace:0pt;mso-t=
able-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"> <t=
r> <td valign=3D"top" align=3D"center" style=3D"padding:0;Margin:0;width:46=
0px"> <table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" role=3D"pre=
sentation" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collap=
se:collapse;border-spacing:0px"> <tr> <td align=3D"left" style=3D"padding:0=
;Margin:0;padding-top:5px;padding-left:10px;font-size:0px"><a target=3D"_bl=
ank" href=3D"https://promaaua.esclick.me/1kPyBsvOz5hW30Rsmj" style=3D"-webk=
it-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exa=
ctly;text-decoration:underline;color:#1376C8;font-size:14px"><img src=3D"ht=
tps://pics.esputnik.com/repository/home/6798/images/msg/40621890/1647347550=
840.gif" alt=3D"prom.ua" style=3D"display:block;border:0;outline:none;text-=
decoration:none;-ms-interpolation-mode:bicubic" title=3D"prom.ua" width=3D"=
138"></a></td> </tr> </table></td> </tr> </table></td> <td style=3D"padding=
:0;Margin:0;width:20px"></td> <td valign=3D"top" style=3D"padding:0;Margin:=
0"> <table cellspacing=3D"0" cellpadding=3D"0" align=3D"right" role=3D"none=
" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collap=
se;border-spacing:0px"> <tr> <td align=3D"left" style=3D"padding:0;Margin:0=
;width:100px"> <table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" ro=
le=3D"presentation" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;bord=
er-collapse:collapse;border-spacing:0px"> <tr> <td style=3D"padding:0;Margi=
n:0"> <table cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"pre=
sentation" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collap=
se:collapse;border-spacing:0px"> <tr> <td align=3D"center" valign=3D"top" w=
idth=3D"50%" id=3D"esd-menu-id-0" style=3D"Margin:0;padding-left:5px;paddin=
g-right:5px;padding-top:10px;padding-bottom:10px;border:0"><a target=3D"_bl=
ank" href=3D"https://promaaua.esclick.me/1kPyDeooOzn0sQDAWj" style=3D"-webk=
it-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exa=
ctly;text-decoration:none;display:block;font-family:Montserrat, 'Google San=
s', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;color:#1376C8;font-size:1=
4px"><img src=3D"https://npgona.stripocdn.email/content/guids/CABINET_61e3f=
dea27224d1c497b1215fc1c9f07/images/1629531332168.png" alt=3D"facebook" titl=
e=3D"facebook" height=3D"35" style=3D"display:inline-block !important;borde=
r:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;vertic=
al-align:middle"></a></td> <td align=3D"center" valign=3D"top" width=3D"50%=
" id=3D"esd-menu-id-1" style=3D"Margin:0;padding-left:5px;padding-right:5px=
;padding-top:10px;padding-bottom:10px;border:0"><a target=3D"_blank" href=
=3D"https://promaaua.esclick.me/1kPyE0nUgZo72hlQ8j" style=3D"-webkit-text-s=
ize-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text=
-decoration:none;display:block;font-family:Montserrat, 'Google Sans', 'Sego=
e UI', Roboto, Arial, Ubuntu, sans-serif;color:#1376C8;font-size:14px"><img=
 src=3D"https://npgona.stripocdn.email/content/guids/CABINET_61e3fdea27224d=
1c497b1215fc1c9f07/images/1629531343024.png" alt=3D"instagram" title=3D"ins=
tagram" height=3D"35" style=3D"display:inline-block !important;border:0;out=
line:none;text-decoration:none;-ms-interpolation-mode:bicubic;vertical-alig=
n:middle"></a></td> </tr> </table></td> </tr> </table></td> </tr> </table><=
/td> </tr> </table></td> </tr> <tr> <td align=3D"left" bgcolor=3D"#8B08F9" =
style=3D"padding:0;Margin:0;padding-top:20px;padding-bottom:20px;background=
-color:#8b08f9;border-radius:0px 0px 12px 12px"> <table cellpadding=3D"0" c=
ellspacing=3D"0" width=3D"100%" role=3D"none" style=3D"mso-table-lspace:0pt=
;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"> <tr> <t=
d align=3D"center" valign=3D"top" style=3D"padding:0;Margin:0;width:600px">=
 <table cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"presenta=
tion" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:co=
llapse;border-spacing:0px"> <tr> <td style=3D"padding:0;Margin:0"> <table c=
ellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"presentation" sty=
le=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;bo=
rder-spacing:0px"> <tr> <td align=3D"center" valign=3D"top" width=3D"33.33%=
" id=3D"esd-menu-id-0" style=3D"Margin:0;padding-left:5px;padding-right:5px=
;padding-top:0px;padding-bottom:0px;border:0"><a target=3D"_blank" href=3D"=
https://promaaua.esclick.me/1kPyEMmAy9pDCzJg0j" style=3D"-webkit-text-size-=
adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-dec=
oration:none;display:block;font-family:Montserrat, 'Google Sans', 'Segoe UI=
', Roboto, Arial, Ubuntu, sans-serif;color:#ffffff;font-size:18px;font-weig=
ht:bold">=D0=97=D0=B0=D1=80=D0=B0=D0=B7 =D0=BA=D1=83=D0=BF=D1=83=D1=8E=D1=
=82=D1=8C</a></td> <td align=3D"center" valign=3D"top" width=3D"33.33%" id=
=3D"esd-menu-id-1" style=3D"Margin:0;padding-left:5px;padding-right:5px;pad=
ding-top:0px;padding-bottom:0px;border:0;border-left:1px solid #bf72ff"><a =
target=3D"_blank" href=3D"https://promaaua.esclick.me/1kPyEikrFjqJNGrwmj" s=
tyle=3D"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-he=
ight-rule:exactly;text-decoration:none;display:block;font-family:Montserrat=
, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;color:#fffff=
f;font-size:18px;font-weight:bold">=D0=94=D0=BE=D0=B4=D0=B0=D1=82=D0=BE=D0=
=BA Prom</a></td> <td align=3D"center" valign=3D"top" width=3D"33.33%" id=
=3D"esd-menu-id-2" style=3D"Margin:0;padding-left:5px;padding-right:5px;pad=
ding-top:0px;padding-bottom:0px;border:0;border-left:1px solid #bf72ff"><a =
target=3D"_blank" href=3D"https://promaaua.esclick.me/1kPyF4jXXJrPXYQC0j" s=
tyle=3D"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-he=
ight-rule:exactly;text-decoration:none;display:block;font-family:Montserrat=
, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;color:#fffff=
f;font-size:18px;font-weight:bold">=D0=9F=D1=80=D0=BE=D0=BC-=D0=BE=D0=BF=D0=
=BB=D0=B0=D1=82=D0=B0</a></td> </tr> </table></td> </tr> </table></td> </tr=
> </table></td> </tr> <tr> <td align=3D"left" style=3D"padding:0;Margin:0">=
 <table cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"none" st=
yle=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;b=
order-spacing:0px"> <tr> <td align=3D"center" valign=3D"top" style=3D"paddi=
ng:0;Margin:0;width:600px"> <table cellpadding=3D"0" cellspacing=3D"0" widt=
h=3D"100%" role=3D"presentation" style=3D"mso-table-lspace:0pt;mso-table-rs=
pace:0pt;border-collapse:collapse;border-spacing:0px"> <tr> <td align=3D"ce=
nter" height=3D"20" style=3D"padding:0;Margin:0"></td> </tr> </table></td> =
</tr> </table></td> </tr> </table></td> </tr> </table> <table cellpadding=
=3D"0" cellspacing=3D"0" align=3D"center" role=3D"none" style=3D"mso-table-=
lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px=
;table-layout:fixed !important;width:100%"> <tr> <td align=3D"center" style=
=3D"padding:0;Margin:0"> <table cellspacing=3D"0" cellpadding=3D"0" bgcolor=
=3D"#ffffff" align=3D"center" role=3D"none" style=3D"mso-table-lspace:0pt;m=
so-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-=
color:#F4F4F9;width:600px"> <tr> <td style=3D"padding:0;Margin:0;padding-le=
ft:20px;padding-right:20px;border-radius:16px 16px 0px 0px;background-color=
:#ffffff" bgcolor=3D"#ffffff" align=3D"left"> <table cellspacing=3D"0" cell=
padding=3D"0" width=3D"100%" role=3D"none" style=3D"mso-table-lspace:0pt;ms=
o-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"> <tr> <td v=
align=3D"top" align=3D"center" style=3D"padding:0;Margin:0;width:560px"> <t=
able width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" role=3D"presentatio=
n" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:colla=
pse;border-spacing:0px"> <tr> <td align=3D"left" style=3D"padding:0;Margin:=
0;padding-top:20px"><p style=3D"Margin:0;-webkit-text-size-adjust:none;-ms-=
text-size-adjust:none;mso-line-height-rule:exactly;font-family:Montserrat, =
'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;line-height:36=
px;color:#01011b;font-size:24px"><strong>=D0=91=D0=B5=D0=B7=D0=BA=D0=BE=D1=
=88=D1=82=D0=BE=D0=B2=D0=BD=D0=B0 =D0=B4=D0=BE=D1=81=D1=82=D0=B0=D0=B2=D0=
=BA=D0=B0</strong></p></td> </tr> </table></td> </tr> </table></td> </tr> <=
tr> <td style=3D"padding:0;Margin:0;padding-left:20px;padding-right:20px;ba=
ckground-color:#ffffff" bgcolor=3D"#ffffff" align=3D"left"><!--[if mso]><ta=
ble style=3D"width:560px" cellpadding=3D"0" cellspacing=3D"0"><tr><td style=
=3D"width:396px" valign=3D"top"><![endif]--> <table cellspacing=3D"0" cellp=
adding=3D"0" align=3D"left" role=3D"none" style=3D"mso-table-lspace:0pt;mso=
-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left"> =
<tr> <td valign=3D"top" align=3D"center" style=3D"padding:0;Margin:0;width:=
396px"> <table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" role=3D"p=
resentation" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-coll=
apse:collapse;border-spacing:0px"> <tr> <td align=3D"left" style=3D"padding=
:0;Margin:0;padding-bottom:15px;padding-top:20px;padding-right:20px"><p sty=
le=3D"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-=
line-height-rule:exactly;font-family:Montserrat, 'Google Sans', 'Segoe UI',=
 Roboto, Arial, Ubuntu, sans-serif;line-height:22.5px;color:#01011b;font-si=
ze:15px">=D0=9E=D1=84=D0=BE=D1=80=D0=BC=D0=BB=D1=8E=D0=B9 =D0=BF=D1=96=D0=
=B4=D0=BF=D0=B8=D1=81=D0=BA=D1=83 =C2=AB=D0=94=D0=BB=D1=8F =D1=81=D0=B2=D0=
=BE=D1=97=D1=85=C2=BB =D0=B7=D0=B0 30 =D0=B3=D1=80=D0=BD/=D0=BC=D1=96=D1=81=
 =D1=82=D0=B0 =D0=BE=D1=82=D1=80=D0=B8=D0=BC=D1=83=D0=B9 =D0=B1=D0=B5=D0=B7=
=D0=BA=D0=BE=D1=88=D1=82=D0=BE=D0=B2=D0=BD=D1=83 =D0=B4=D0=BE=D1=81=D1=82=
=D0=B0=D0=B2=D0=BA=D1=83 =D0=B4=D0=BE =D0=9D=D0=BE=D0=B2=D0=BE=D1=97 =D0=BF=
=D0=BE=D1=88=D1=82=D0=B8 =D1=82=D0=B0 =D0=BC=D0=B0=D0=B3=D0=B0=D0=B7=D0=B8=
=D0=BD=D1=96=D0=B2 Rozetka.</p><p style=3D"Margin:0;-webkit-text-size-adjus=
t:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:M=
ontserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;lin=
e-height:22.5px;color:#01011b;font-size:15px"><br></p><p style=3D"Margin:0;=
-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rul=
e:exactly;font-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, Arial,=
 Ubuntu, sans-serif;line-height:22.5px;color:#01011b;font-size:15px">=D0=9A=
=D1=83=D0=BF=D1=83=D0=B9 =D0=B2=D0=B8=D0=B3=D1=96=D0=B4=D0=BD=D0=BE =D0=BD=
=D0=B0 =D0=9F=D1=80=D0=BE=D0=BC=D1=96 =E2=80=93 =D0=B1=D0=B5=D0=B7=D0=BA=D0=
=BE=D1=88=D1=82=D0=BE=D0=B2=D0=BD=D0=B0 =D0=B4=D0=BE=D1=81=D1=82=D0=B0=D0=
=B2=D0=BA=D0=B0 =D0=B2=D0=B6=D0=B5 =D1=87=D0=B5=D0=BA=D0=B0=D1=94 =D0=BD=D0=
=B0 =D1=82=D0=B5=D0=B1=D0=B5! =F0=9F=98=89</p></td> </tr> </table></td> </t=
r> </table><!--[if mso]></td><td style=3D"width:164px" valign=3D"top"><![en=
dif]--> <table cellspacing=3D"0" cellpadding=3D"0" align=3D"right" role=3D"=
none" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:co=
llapse;border-spacing:0px"> <tr> <td align=3D"left" style=3D"padding:0;Marg=
in:0;width:164px"> <table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0=
" role=3D"presentation" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;=
border-collapse:collapse;border-spacing:0px"> <tr> <td style=3D"padding:0;M=
argin:0;font-size:0px" align=3D"center"><a target=3D"_blank" href=3D"https:=
//promaaua.esclick.me/1kPyFQiDotsVhpyS8j" style=3D"-webkit-text-size-adjust=
:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoratio=
n:underline;color:#8B08F9;font-size:22px"><img src=3D"https://pics.esputnik=
.com/repository/home/6798/images/msg/40621890/1716214465588.png" alt=3D"=D0=
=9F=D1=96=D0=B4=D0=BF=D0=B8=D1=81=D0=BA=D0=B0 =C2=AB=D0=94=D0=BB=D1=8F =D1=
=81=D0=B2=D0=BE=D1=97=D1=85=C2=BB " style=3D"display:block;border:0;outline=
:none;text-decoration:none;-ms-interpolation-mode:bicubic" title=3D"=D0=9F=
=D1=96=D0=B4=D0=BF=D0=B8=D1=81=D0=BA=D0=B0 =C2=AB=D0=94=D0=BB=D1=8F =D1=81=
=D0=B2=D0=BE=D1=97=D1=85=C2=BB " width=3D"160"></a></td> </tr> </table></td=
> </tr> </table><!--[if mso]></td></tr></table><![endif]--></td> </tr> <tr>=
 <td align=3D"left" style=3D"padding:0;Margin:0"> <table cellpadding=3D"0" =
cellspacing=3D"0" width=3D"100%" role=3D"none" style=3D"mso-table-lspace:0p=
t;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"> <tr> <=
td align=3D"center" valign=3D"top" style=3D"padding:0;Margin:0;width:600px"=
> <table cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" bgcolor=3D"#fff=
fff" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:col=
lapse;border-spacing:0px;background-color:#ffffff" role=3D"presentation"> <=
tr> <td align=3D"center" style=3D"padding:0;Margin:0;padding-top:15px;paddi=
ng-left:20px;padding-right:20px;font-size:0px"><a target=3D"_blank" href=3D=
"https://promaaua.esclick.me/1kPyFmgu6Ttbs7Wiuj" style=3D"-webkit-text-size=
-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-de=
coration:underline;color:#8B08F9;font-size:22px"><img src=3D"https://pics.e=
sputnik.com/repository/home/6798/images/msg/40621890/1754036530511.png" alt=
=3D"=D0=A3=D0=BC=D0=BE=D0=B2=D0=B8 =D0=BF=D1=96=D0=B4=D0=BF=D0=B8=D1=81=D0=
=BA=D0=B8 =C2=AB=D0=94=D0=BB=D1=8F =D1=81=D0=B2=D0=BE=D1=97=D1=85=C2=BB " s=
tyle=3D"display:block;border:0;outline:none;text-decoration:none;-ms-interp=
olation-mode:bicubic" width=3D"515" title=3D"=D0=A3=D0=BC=D0=BE=D0=B2=D0=B8=
 =D0=BF=D1=96=D0=B4=D0=BF=D0=B8=D1=81=D0=BA=D0=B8 =C2=AB=D0=94=D0=BB=D1=8F =
=D1=81=D0=B2=D0=BE=D1=97=D1=85=C2=BB "></a></td> </tr> </table></td> </tr> =
</table></td> </tr> <tr> <td align=3D"left" style=3D"padding:0;Margin:0"> <=
table cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"none" styl=
e=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;bor=
der-spacing:0px"> <tr> <td align=3D"left" bgcolor=3D"#ffffff" style=3D"padd=
ing:0;Margin:0;padding-top:10px;padding-left:20px;padding-right:20px"><p st=
yle=3D"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso=
-line-height-rule:exactly;font-family:Montserrat, 'Google Sans', 'Segoe UI'=
, Roboto, Arial, Ubuntu, sans-serif;line-height:22.5px;color:#01011B;font-s=
ize:15px"><i>*=D0=94=D0=BE 31 =D0=BB=D0=B8=D0=BF=D0=BD=D1=8F 2025 =D1=80=D0=
=BE=D0=BA=D1=83 =D0=B2=D0=BA=D0=BB=D1=8E=D1=87=D0=BD=D0=BE =D0=BF=D1=96=D0=
=B4=D0=BF=D0=B8=D1=81=D0=BA=D0=B0 =D0=B4=D1=96=D1=94 =D0=B2=D1=96=D0=B4 100=
 =D0=B3=D1=80=D0=BD, =D0=B4=D0=B0=D0=BB=D1=96 =E2=80=93 =D0=B2=D1=96=D0=B4 =
400 =D0=B3=D1=80=D0=BD.&nbsp;</i><i> <a target=3D"_blank" href=3D"https://p=
romaaua.esclick.me/1kPyG8faO3ui2P4y8j" style=3D"-webkit-text-size-adjust:no=
ne;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:u=
nderline;color:#8B08F9;font-size:15px">=D0=94=D0=B5=D1=82=D0=B0=D0=BB=D1=8C=
=D0=BD=D1=96=D1=88=D0=B5</a></i></p></td> </tr> </table></td> </tr> <tr> <t=
d align=3D"left" bgcolor=3D"#ffffff" style=3D"padding:0;Margin:0;background=
-color:#ffffff;border-radius:0px 0px 16px 16px"> <table width=3D"100%" cell=
spacing=3D"0" cellpadding=3D"0" role=3D"none" style=3D"mso-table-lspace:0pt=
;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"> <tr> <t=
d valign=3D"top" align=3D"center" style=3D"padding:0;Margin:0;width:600px">=
 <table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" role=3D"presenta=
tion" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:co=
llapse;border-spacing:0px"> <tr> <td align=3D"center" style=3D"padding:0;Ma=
rgin:0;padding-top:20px;padding-bottom:20px"><span class=3D"es-button-borde=
r" style=3D"border-style:solid;border-color:#2CB543;background:#8B08F9;bord=
er-width:0px;display:inline-block;border-radius:8px;width:auto"><a href=3D"=
https://promaaua.esclick.me/1kPyCEu5GficDI08Oj" class=3D"es-button es-butto=
n-1653046069594" target=3D"_blank" style=3D"mso-style-priority:100 !importa=
nt;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:=
none;mso-line-height-rule:exactly;color:#FFFFFF;font-size:20px;display:inli=
ne-block;background:#8B08F9;border-radius:8px;font-family:Montserrat, 'Goog=
le Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;font-weight:bold;fo=
nt-style:normal;line-height:24px;width:auto;text-align:center;padding:15px =
37px 15px 36px;mso-padding-alt:0;mso-border-alt:10px solid #8B08F9">=D0=9E=
=D1=84=D0=BE=D1=80=D0=BC=D0=B8=D1=82=D0=B8 =D0=BF=D1=96=D0=B4=D0=BF=D0=B8=
=D1=81=D0=BA=D1=83</a></span></td> </tr> </table></td> </tr> </table></td> =
</tr> </table></td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"=
0" align=3D"center" role=3D"none" style=3D"mso-table-lspace:0pt;mso-table-r=
space:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !i=
mportant;width:100%"> <tr> <td align=3D"center" style=3D"padding:0;Margin:0=
"> <table bgcolor=3D"#ffffff" align=3D"center" cellpadding=3D"0" cellspacin=
g=3D"0" role=3D"none" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;bo=
rder-collapse:collapse;border-spacing:0px;background-color:#F4F4F9;width:60=
0px"> <tr> <td align=3D"left" style=3D"padding:0;Margin:0"> <table cellpadd=
ing=3D"0" cellspacing=3D"0" width=3D"100%" role=3D"none" style=3D"mso-table=
-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0p=
x"> <tr> <td align=3D"center" valign=3D"top" style=3D"padding:0;Margin:0;wi=
dth:600px"> <table cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" role=
=3D"presentation" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border=
-collapse:collapse;border-spacing:0px"> <tr> <td align=3D"center" style=3D"=
padding:0;Margin:0;padding-bottom:20px;padding-left:20px;padding-right:20px=
;font-size:0"> <table border=3D"0" width=3D"100%" height=3D"100%" cellpaddi=
ng=3D"0" cellspacing=3D"0" role=3D"presentation" style=3D"mso-table-lspace:=
0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"> <tr>=
 <td style=3D"padding:0;Margin:0;border-bottom:0px solid #cccccc;background=
:unset;height:0px;width:100%;margin:0px"></td> </tr> </table></td> </tr> </=
table></td> </tr> </table></td> </tr> </table></td> </tr> </table> <table c=
ellpadding=3D"0" cellspacing=3D"0" align=3D"center" role=3D"none" style=3D"=
mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-s=
pacing:0px;table-layout:fixed !important;width:100%"> <tr> <td align=3D"cen=
ter" style=3D"padding:0;Margin:0"> <table bgcolor=3D"#ffffff" align=3D"cent=
er" cellpadding=3D"0" cellspacing=3D"0" role=3D"none" style=3D"mso-table-ls=
pace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;b=
ackground-color:#F4F4F9;width:600px"> <tr> <td align=3D"left" style=3D"padd=
ing:0;Margin:0"> <table cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" =
role=3D"none" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-col=
lapse:collapse;border-spacing:0px"> <tr> <td align=3D"center" valign=3D"top=
" style=3D"padding:0;Margin:0;width:600px"> <table cellpadding=3D"0" cellsp=
acing=3D"0" width=3D"100%" role=3D"presentation" style=3D"mso-table-lspace:=
0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"> <tr>=
 <td align=3D"center" style=3D"padding:0;Margin:0;font-size:0px"><a target=
=3D"_blank" href=3D"https://promaaua.esclick.me/1kPyCaslYFjiNZYOuj" style=
=3D"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height=
-rule:exactly;text-decoration:underline;color:#8B08F9;font-size:22px"><img =
src=3D"https://pics.esputnik.com/repository/home/6798/images/msg/40621890/1=
715933081052.png" alt=3D"=D0=97=D0=B0=D0=B2=D0=B0=D0=BD=D1=82=D0=B0=D0=B6=
=D0=B8=D1=82=D0=B8" style=3D"display:block;border:0;outline:none;text-decor=
ation:none;-ms-interpolation-mode:bicubic" width=3D"600" title=3D"=D0=97=D0=
=B0=D0=B2=D0=B0=D0=BD=D1=82=D0=B0=D0=B6=D0=B8=D1=82=D0=B8"></a></td> </tr> =
</table></td> </tr> </table></td> </tr> </table></td> </tr> </table> <table=
 cellpadding=3D"0" cellspacing=3D"0" align=3D"center" role=3D"none" style=
=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;bord=
er-spacing:0px;table-layout:fixed !important;width:100%"> <tr> <td align=3D=
"center" style=3D"padding:0;Margin:0"> <table bgcolor=3D"#ffffff" align=3D"=
center" cellpadding=3D"0" cellspacing=3D"0" role=3D"none" style=3D"mso-tabl=
e-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0=
px;background-color:#F4F4F9;width:600px"> <tr> <td align=3D"left" style=3D"=
padding:0;Margin:0"> <table cellpadding=3D"0" cellspacing=3D"0" width=3D"10=
0%" role=3D"none" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border=
-collapse:collapse;border-spacing:0px"> <tr> <td align=3D"center" valign=3D=
"top" style=3D"padding:0;Margin:0;width:600px"> <table cellpadding=3D"0" ce=
llspacing=3D"0" width=3D"100%" role=3D"presentation" style=3D"mso-table-lsp=
ace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"> =
<tr> <td align=3D"center" style=3D"padding:0;Margin:0;padding-bottom:20px;p=
adding-left:20px;padding-right:20px;font-size:0"> <table border=3D"0" width=
=3D"100%" height=3D"100%" cellpadding=3D"0" cellspacing=3D"0" role=3D"prese=
ntation" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse=
:collapse;border-spacing:0px"> <tr> <td style=3D"padding:0;Margin:0;border-=
bottom:0px solid #cccccc;background:unset;height:0px;width:100%;margin:0px"=
></td> </tr> </table></td> </tr> </table></td> </tr> </table></td> </tr> </=
table></td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" align=
=3D"center" role=3D"none" style=3D"mso-table-lspace:0pt;mso-table-rspace:0p=
t;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important=
;width:100%"> <tr> <td align=3D"center" style=3D"padding:0;Margin:0"> <tabl=
e bgcolor=3D"#ffffff" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" =
role=3D"none" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-col=
lapse:collapse;border-spacing:0px;background-color:#F4F4F9;width:600px"> <t=
r> <td align=3D"left" style=3D"padding:0;Margin:0"> <table cellpadding=3D"0=
" cellspacing=3D"0" width=3D"100%" role=3D"none" style=3D"mso-table-lspace:=
0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"> <tr>=
 <td valign=3D"top" align=3D"center" style=3D"padding:0;Margin:0;width:600p=
x"> <table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" role=3D"prese=
ntation" style=3D"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse=
:collapse;border-spacing:0px"> <tr> <td align=3D"left" style=3D"padding:0;M=
argin:0;padding-bottom:15px"><p style=3D"Margin:0;-webkit-text-size-adjust:=
none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Mon=
tserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-serif;line-=
height:30px;color:#999999;font-size:20px">=D0=92=D0=B8 =D0=BE=D1=82=D1=80=
=D0=B8=D0=BC=D0=B0=D0=BB=D0=B8 =D1=86=D1=8E =D1=80=D0=BE=D0=B7=D1=81=D0=B8=
=D0=BB=D0=BA=D1=83, =D0=BE=D1=81=D0=BA=D1=96=D0=BB=D1=8C=D0=BA=D0=B8 =D1=80=
=D0=B5=D1=94=D1=81=D1=82=D1=80=D1=83=D0=B2=D0=B0=D0=BB=D0=B8=D1=81=D1=8F =
=D0=BD=D0=B0 <a target=3D"_blank" style=3D"-webkit-text-size-adjust:none;-m=
s-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underl=
ine;color:#8b08f9;font-size:20px" href=3D"https://promaaua.esclick.me/1kPyC=
wrRppkoXr6emj">prom.ua</a></p></td> </tr> <tr> <td align=3D"left" style=3D"=
padding:0;Margin:0;padding-bottom:35px"><p style=3D"Margin:0;-webkit-text-s=
ize-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font=
-family:Montserrat, 'Google Sans', 'Segoe UI', Roboto, Arial, Ubuntu, sans-=
serif;line-height:33px;color:#01011B;font-size:22px"><a id=3D"unsubscribe" =
style=3D"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-h=
eight-rule:exactly;text-decoration:underline;color:#8b08f9;font-size:20px" =
href=3D"https://promaaua.esclick.me/1kPyDIq87Plui8euGj">=D0=92=D1=96=D0=B4=
=D0=BF=D0=B8=D1=81=D0=B0=D1=82=D0=B8=D1=81=D1=8F =D0=B2=D1=96=D0=B4 =D1=80=
=D0=BE=D0=B7=D1=81=D0=B8=D0=BB=D0=BA=D0=B8</a></p></td> </tr> </table></td>=
 </tr> </table></td> </tr> </table></td> </tr> </table></td> </tr> </table>=
 </div> <div itemscope itemtype=3D"http://schema.org/Organization"> <meta i=
temprop=3D"logo" content=3D"https://pics.esputnik.com/repository/home/6798/=
images/google-promo/recent/1613725023742.png"> </div> </body></html>
------=_Part_1450349_1419197779.1758120353761--
