Return-Path: <mediainc2020@gmail.com>
Received: from mail-ej1-f46.google.com (209.85.218.46) by satipe.disaki.es for <info@tagsignature.com>; Wed, 17 Sep 2025 16:52:48 +0200 (envelope-from <mediainc2020@gmail.com>)
Received: by mail-ej1-f46.google.com with SMTP id a640c23a62f3a-afcb7ae6ed0so1036606666b.3
        for <info@tagsignature.com>; Wed, 17 Sep 2025 07:52:48 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20230601; t=1758120768; x=1758725568; darn=tagsignature.com;
        h=to:subject:message-id:date:from:mime-version:from:to:cc:subject
         :date:message-id:reply-to;
        bh=Up+XL5DPVGnNcBYa4Fe/aOEVFUO2QklgZVwFWYWjs5c=;
        b=cYd2UuQT4cTMwiUAL/COtQNuhbwSL1VO9omrskqG9D2I4SlVwVMjdnzjif4ZcftSjl
         bBmj5juZA2Er1xeI6OTtVAUtCn3QlTZPkOgOh88AYXrUUtWIGcwPHbLtl1XlQS89MY3l
         JtPzs4233Rbl9vvbLskNRCXCXacx3zvskO49+3ToDSX8iRRT2dlV7D6VZDHKrdGqz7uE
         dVWC0w0BnZhfugS8muw6DBkRlyuvJa0EZgdLCqyXS917wJ3n5qnN5ZXAMLJibSLruO8Y
         A2YjT0kC0Vuqha6cd0nbnEf7M42bSbSVwtSfR3trD5bBaN/G3bMaXK08ZF12ySOTtk2e
         TCcg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1758120768; x=1758725568;
        h=to:subject:message-id:date:from:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=Up+XL5DPVGnNcBYa4Fe/aOEVFUO2QklgZVwFWYWjs5c=;
        b=WYW3fecLZcG8IPRgI6HhZsp4BrL2ZZZ25IDyXEp3Ds99ClKA709TXgTdU75YgE1kXO
         gWAsD8Dgn2ASf91l3g0fPcyAZK+uwHGnoOEMP4IfqmhmQENGMpZSHqOYTH26ucWT5WZD
         JcuJ5LUonZYwUYawMN7XsLRjTXptoyzvXHR2krbGqjK8eiNtQR6deE/vf3vnz8mn1suW
         7vxLteYrmZnCevoC6AP0MTaNMtlGgaxgdNYWZgSRfxdbvxjCikb80AtahEKNQpQuVTj/
         bhnVkJXH/9F3Cf5IMEYNfVLjUFeLH+2hqwKHUzqJLghysSJw/ui11VFjoD4YtoLoluvf
         VJxg==
X-Forwarded-Encrypted: i=1; AJvYcCXWOMcAEIMCMbj2k/azICZlIW2R0fYLBBMglVZKLgB1ZlnQIBRQXVMN3XHZv8ncuZYdpRxj@tagsignature.com
X-Gm-Message-State: AOJu0YzvnCVWce5hqmhZcOUnNp6VduWyP4mDywQThduJL/ITIoQbXySs
	cX/yVKdnTfIXnQ+7tFYcmLRYClx5oB9eJfuy6rL1hKp9KPz70HkrTWmgsyK0CibmxuwDvfrahJX
	eRiM2OTZAAjj7KqRKwcT3XVzYW1PBFGk=
X-Gm-Gg: ASbGnctX850TR5H1eeIejp9FMjYfN2G14sSpdaXnL3nZUNavbiv7Kusiw6/fcwlS9d1
	4/NxDsryCCnz5UkuxHyncRymMrPenbKzXen9qO6PSa+mQvtY42c9PvaCxaPqE1JmLb47rLdwwOU
	PnrCatFk5oG03kLz4frlziWTZNIEQmOQYeNXfe2ObLM/v5Y79f7Vs+JM+AWldhJfdPqkVMxw0e/
	m79c0o/
X-Google-Smtp-Source: AGHT+IEY51uNUYoQN046cT46vJvO3Fwaalq9nWN9lvmbOyqsi+Ts3F1CbvULSf+ASplsKLIDQ3EpiBRu0cZaEcFYEhw=
X-Received: by 2002:a17:907:9305:b0:b09:2331:f150 with SMTP id
 a640c23a62f3a-b1bb216c348mr241798866b.16.1758120768262; Wed, 17 Sep 2025
 07:52:48 -0700 (PDT)
MIME-Version: 1.0
From: Jan andre <mediainc2020@gmail.com>
Date: Wed, 17 Sep 2025 15:54:50 +0100
X-Gm-Features: AS18NWBCuGM4PLfwN4lA-0mxUSzf34MUHrzH4zK4Qrv71dTOid-P9BZpxBjmbpY
Message-ID: <CAKaBx8s5H2JRZRzBL3ku08AzdoOQfxU0Ge4d8QRh1anM7Ym75Q@mail.gmail.com>
Subject: test mail server
To: info@eminenteffect.com, info@tagsignature.com, info@forwarderpro.com, 
	info@laroccagunworks.com, info@tangoacademypasadena.com, 
	info@unibank-armenia.com, info@iexpressusa.com, info@fairoakssutler.com, 
	info@justoutofreach.com, info@nachalatbinyamin.com, info@goingunderground.net, 
	info@sdappraisers.net, info@tnoutdoorsmen.com, info@pestcontrolefinder.com, 
	info@oriontv.net, info@colormebutterfly.com, info@superplayusa.com, 
	info@tallerdecomputo.com, info@ironflowerfitnessmiami.com, 
	info@jennamcwilliams.com
Content-Type: multipart/alternative; boundary="000000000000dd59ff063f00635f"

--000000000000dd59ff063f00635f
Content-Type: text/plain; charset="UTF-8"

sdfsd

--000000000000dd59ff063f00635f
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">sdfsd</div>

--000000000000dd59ff063f00635f--
